force-app/main/default/objects/Webinars__c/Webinars__c.object-meta.xml
<CustomObject>
    <label>Webinars</label>
    <nameField>
        <label>Webinars Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Webinars</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Webinars__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Field used for the care app to filter Webinars based on country</description>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>VIEW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinars__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Field used for the care app to filter Webinars</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIEWforce</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
            <value>
                <fullName>KYC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Webinars__c/fields/Video_url__c.field-meta.xml
<CustomField>
    <fullName>Video_url__c</fullName>
    <label>Video URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/WebinarController.cls
// Created June 2020 - Mia Genovese, Fluido
// Used for the View Academy App
public with sharing class WebinarController {
    @AuraEnabled(cacheable=true)
    public static Webinars__c[] getWebinarList() {
        return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate
                from Webinars__c];
    }

    @AuraEnabled(cacheable=true)
    public static Webinars__c[] getFilteredWebinars(List<String> types, List<String> countries, String searchTerm) {
       if (types == null && countries == null && searchTerm == null|| (types.isEmpty() && countries.isEmpty() && searchTerm == '' )) {
            return getWebinarList();
       } 
       else if((types != null || !types.isEmpty()) && ( (countries == null || countries.isEmpty()) && (searchTerm == null || searchTerm == '' )) ) {
            return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                    from Webinars__c
                    where Type__c in :types];
       }
       else if((types == null || types.isEmpty()) && (countries != null || !countries.isEmpty()) && (searchTerm == null || searchTerm == '')) {
            return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                    from Webinars__c
                    where Country__c in :countries];
       }
       else if (!types.isEmpty() && !countries.isEmpty() && (searchTerm == null || searchTerm == '')) {
        System.debug('##hallooo');
            return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                    from Webinars__c
                    where Type__c in :types
                    and Country__c in :countries];
       }
       else if(types == null && countries == null && searchTerm != null|| (types.isEmpty() && countries.isEmpty() && searchTerm != '' )){
            searchTerm = '%'+ searchTerm +'%';
            return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                    from Webinars__c
                    where Name LIKE :searchTerm or Description__c LIKE :searchTerm];
       }
       else if(!types.isEmpty() && !countries.isEmpty() && (searchTerm != null || searchTerm != '')){
            searchTerm = '%'+ searchTerm +'%';
            return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                    from Webinars__c
                    where (Name LIKE :searchTerm or Description__c LIKE :searchTerm)
                    and Type__c in :types
                    and Country__c in :countries];
       }
       else if((types == null || types.isEmpty()) && (countries != null || !countries.isEmpty()) && (searchTerm != null || searchTerm != '')){
          searchTerm = '%'+ searchTerm +'%';
          return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                  from Webinars__c
                  where (Name LIKE :searchTerm or Description__c LIKE :searchTerm)
                  and Country__c in :countries];
       }
       else if((types != null || !types.isEmpty()) && ( (countries == null || countries.isEmpty()) && (searchTerm != null || searchTerm != '' ))){
          searchTerm = '%'+ searchTerm +'%';
          return [select Id, Name, Description__c, Video_url__c, Type__c, Country__c, LastModifiedDate 
                  from Webinars__c
                  where (Name LIKE :searchTerm or Description__c LIKE :searchTerm)
                  and Type__c in :types];
       }
       else {
           return null;
       }
    }
    @AuraEnabled(cacheable=true)
    public static Boolean getUserPermissions(String userId){
            System.debug('userId ' + userId);
        Boolean hasPermission = false;
        List<PermissionSetAssignment> currentUserPermissions = [select Id, PermissionSet.Name, AssigneeId
                                                                from PermissionSetAssignment
                                                                where AssigneeId = :userId ];
        for(PermissionSetAssignment psa : currentUserPermissions){
                if(psa.PermissionSet.Name == 'manage_Academy'){
                        hasPermission = true;
                    	return hasPermission;
                }
        }
        Id sysAdmin = [select Id, Name from Profile where Name = 'System Administrator'].Id;
        Id profileId = UserInfo.getProfileId();
        if(profileId == sysAdmin){
                hasPermission = true;
        }
        return hasPermission;  
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getCountryPicklistValues(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Webinars__c.Country__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
                options.add(String.valueOf(f.getLabel()));
        }
        System.debug('##country options' + options);
        return options;
    }

    @AuraEnabled(cacheable=true)
    public static List<String> getTypePicklistValues(){
        List<String> options = new List<String>();
        Schema.DescribeFieldResult fieldResult = Webinars__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry f : ple){
                options.add(String.valueOf(f.getLabel()));
        }
        System.debug('##country options' + options);
        return options;
    }
}