force-app/main/default/objects/Action_Plan_Automation__mdt/Action_Plan_Automation__mdt.object-meta.xml
<CustomObject>
    <label>Action Plan Automation</label>
    <pluralLabel>Action Plan Automations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Number_of_days_before_creation__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_before_creation__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Number of days before creation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AptActionPlanCreationScheduleTest.cls
/**
 * Created by jozef on 18. 5. 2023.
 */

@IsTest
private class AptActionPlanCreationScheduleTest {
    @IsTest
    static void testBehavior() {
        //10:17:06.27 (64843315)|USER_DEBUG|[3]|DEBUG|Action_Plan_Automation__mdt:{Label=Notification, MasterLabel=Notification, SystemModstamp=2023-05-18 07:19:51, Number_of_days_before_creation__c=10, Language=no, QualifiedApiName=Notification, Id=m043L0000000TCY, DeveloperName=Notification, NamespacePrefix=null}
        String cron_exp = '0 0 0 3 9 ? 2042';
        String jobId = System.schedule('testAptActionPlanScheduleTest',
                cron_exp, new AptActionPlanCreationSchedule());
    }
}