force-app/main/default/objects/Action_Plan_Automation__mdt/Action_Plan_Automation__mdt.object-meta.xml
<CustomObject>
    <label>Action Plan Automation</label>
    <pluralLabel>Action Plan Automations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <defaultValue>&quot;1.12&quot;</defaultValue>
    <description>Day and Month when automatic process of Action plan creation starts.</description>
    <inlineHelpText>Day and Month when automatic process of Action plan creation starts. Process is scheduled separately. Format: D.MM</inlineHelpText>
    <label>Creation Date</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Notification_Body__c.field-meta.xml
<CustomField>
    <fullName>Notification_Body__c</fullName>
    <label>Notification Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Notification_Title__c.field-meta.xml
<CustomField>
    <fullName>Notification_Title__c</fullName>
    <label>Notification Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Number_of_days_before_creation__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_before_creation__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Number of days before creation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AptActionPlanNotifyBatchTest.cls
/**
 * Created by jozef on 17. 5. 2023.
 */

@IsTest
private class AptActionPlanNotifyBatchTest {
    /*
     Action_Plan_Automation__mdt conf = Action_Plan_Automation__mdt.getInstance('Notification');
     ID batchprocessid = Database.executeBatch(new AptActionPlanNotifyBatch(conf), 150);
     */

    @TestSetup static void setup() {
        AptUtilDataTest.setup();
    }
    @IsTest
    static void testBehavior() {
        AptUtilDataTest.createActionPlan();
        Test.StartTest();
        AptActionPlanNotifyBatch notifyBatch = new AptActionPlanNotifyBatch(getConf());
        ID batchprocessid = Database.executeBatch(notifyBatch, 150);
        Test.StopTest();
    }

    static Action_Plan_Automation__mdt getConf(){
        Action_Plan_Automation__mdt conf = new Action_Plan_Automation__mdt();
        conf.DeveloperName = 'Notification';
        conf.Label = 'Notification';
        conf.Creation_Date__c = '1.12';
        conf.Number_of_days_before_creation__c = 10;
        conf.Notification_Body__c = 'Action Plan for fiscal year {0} for Contract {1} is going to be created within {2} days';
        conf.Notification_Title__c = 'Title';
        return conf;
    }
}