force-app/main/default/objects/Action_Plan_Automation__mdt/Action_Plan_Automation__mdt.object-meta.xml
<CustomObject>
    <label>Action Plan Automation</label>
    <pluralLabel>Action Plan Automations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Creation_Date__c</fullName>
    <defaultValue>&quot;1.12&quot;</defaultValue>
    <description>Day and Month when automatic process of Action plan creation starts.</description>
    <inlineHelpText>Day and Month when automatic process of Action plan creation starts. Process is scheduled separately. Format: D.MM</inlineHelpText>
    <label>Creation Date</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Automation__mdt/fields/Number_of_days_before_creation__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days_before_creation__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Number of days before creation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AptActionPlanNotifyScheduleTest.cls
/**
 * Created by jozef on 17. 5. 2023.
 */

@IsTest
private class AptActionPlanNotifyScheduleTest {
   /*
    @TestSetup
    static void setUp(){
        Action_Plan_Automation__mdt conf = new Action_Plan_Automation__mdt();
        conf.DeveloperName = 'Notification';
        conf.Label = 'Notification';
        conf.Creation_Date__c = '1.12';
        conf.Number_of_days_before_creation__c = 10;
    }*/

    @IsTest
    static void testBehavior() {
        String cron_exp = '0 0 0 3 9 ? 2042';
        Test.startTest();
        String jobId = System.schedule('testAptActionPlanScheduleTest',
                cron_exp, new AptActionPlanNotifySchedule());
        Test.stopTest();
    }
}