force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The Start Date of the Action Plan</description>
    <inlineHelpText>The Start Date of the Action Plan</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AptFiscalYearSelectorController.cls
public class AptFiscalYearSelectorController {
	@AuraEnabled
    public static List<String> initYears(String contractId){
        Integer currentYear = System.Today().year();
        Date startDate = [SELECT Id, StartDate__c FROM Contract__c WHERE Id = :contractId LIMIT 1].StartDate__c;
        List<String> years = new List<String>();
        if (startDate != null) {
            Integer startYear = startDate.year();
            startYear = startYear;
            for (Integer i=startYear; i<=currentYear+1; i++) {
                years.add(String.valueOf(i));
            }
        } else {
           for (Integer i=currentYear; i<=currentYear+1; i++) {
                years.add(String.valueOf(i));
           } 
        }
        return years;
    }
    
    @AuraEnabled
    public static List<ActionPlan__c> fetchActionPlansForYears(String contractId, String fiscalYear){
        if (!String.isBlank(fiscalYear)) {
            return [SELECT Id, Name FROM ActionPlan__c WHERE Contract__c = :contractId AND FiscalYear__c =:fiscalYear];
        } else {
            return new List<ActionPlan__c>();
        }
        
    }
}