force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00NR0000000VZZ8MAO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/APTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task detail</description>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>ActionPlan__c</referenceTo>
    <relationshipName>R00NR0000000VccFMAS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/ActionPlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>ActionPlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action plan template from which was task created in ActionPlan. Used to identify when task from various templates are in the ActionPlan (for example when ActionPlan is generated from Contract with predefined various templates using)</description>
    <label>AP Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values in custom settings.</description>
    <label>Assigned Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Assigned_Type__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Type__c</fullName>
    <label>Assigned Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Autorisert regnskapsfører</fullName>
            </value>
            <value>
                <fullName>User Saksbehandler</fullName>
                <default>true</default>
                <label>User Saksbehandler</label>
            </value>
            <value>
                <fullName>Kundens kontaktperson</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Attachment_Status__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Status__c</fullName>
    <label>Attachment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>SENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/AttachmentHeader__c.field-meta.xml
<CustomField>
    <fullName>AttachmentHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AttachmentHeader</label>
    <referenceTo>AttachmentHeader__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Tertial</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/IsMandatory__c.field-meta.xml
<CustomField>
    <fullName>IsMandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/IsVisible__c.field-meta.xml
<CustomField>
    <fullName>IsVisible__c</fullName>
    <defaultValue>true</defaultValue>
    <label>IsVisible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_10__c.field-meta.xml
<CustomField>
    <fullName>Period_10__c</fullName>
    <label>Period 10</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_3__c.field-meta.xml
<CustomField>
    <fullName>Period_3__c</fullName>
    <label>Period 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period 6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_7__c.field-meta.xml
<CustomField>
    <fullName>Period_7__c</fullName>
    <label>Period 7</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/SendEmail__c.field-meta.xml
<CustomField>
    <fullName>SendEmail__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Send Email Notification of Task creation.</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Skip_Weekends__c.field-meta.xml
<CustomField>
    <fullName>Skip_Weekends__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Weekends</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <label>TaskId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/taskIndex__c.field-meta.xml
<CustomField>
    <fullName>taskIndex__c</fullName>
    <label>taskIndex</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/TemplateStaticPeriodDates__c.field-meta.xml
<CustomField>
    <fullName>TemplateStaticPeriodDates__c</fullName>
    <description>static periods loaded from template task when action plan created, 
does not change when date in template task is changed
semicolon separated ISO format date values f.e. ;;;;;;;2016-12-31;;;;</description>
    <label>Template Static Period Dates</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/TemplateStaticPeriods__c.field-meta.xml
<CustomField>
    <fullName>TemplateStaticPeriods__c</fullName>
    <description>Identify which periods are static and loaded from template.</description>
    <label>Template Static Periods</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttachmentHeader__c/AttachmentHeader__c.object-meta.xml
<CustomObject>
    <label>AttachmentHeader</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttachmentHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AptActionPlanUtilTest.cls
/**
 * Created by jozef on 4. 5. 2023.
 */

@IsTest
private class AptActionPlanUtilTest {
    @testSetup static void setup() {
        AptUtilDataTest.setup();
    }
    @IsTest
    static void savePlanTest() {
        Id apId = null;
        Id userId = UserInfo.getUserId();
        Id tempId = AptUtilDataTest.createTemplatePlan().id;
        Id attHeaderId = AptUtilDataTest.createAttachmentHeader().id;
        String apTasksJSON = '[{"Task_Number__c":230,"Subject__c":"Avstemming a-melding (skyldig skatt/aga terminvis)",' +
                '"Frequency__c":"Bi-monthly","Reminder__c":true,"ActionPlanTemplate__c":"'+ tempId + '",' +
                '"Assigned_Role__c":"Payroll Officer","User__c":"'+ userId + '","taskIndex__c":0,' +
                '"IsMandatory__c":true,"Skip_Weekends__c":false,"IsVisible__c":true,' +
                '"Period_1__c":"2019-09-07","Period_2__c":"2019-11-11",'+
                '"AttachmentHeader__c":"'+ attHeaderId + '"}]';
        String delTasksJSON = '[]';
        String contractId = AptUtilDataTest.createContract().id;
        String fiscalYear = String.valueOf(System.today().year());
        String planName = 'Customer Norway 2019 Operational';
        Boolean skipWeekend = true;

        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new AptContractTriggerHandlerMock.CreateTeamSiteHelper_Mock());
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        //Insert
        AptActionPlanController.savePlan(apId, apTasksJSON, delTasksJSON,
                contractId, fiscalYear, planName, skipWeekend);

        ActionPlan__c ap = [SELECT id FROM ActionPlan__c ];
        apId = ap.id;
        APTaskTemplate__c aptInserted = [SELECT id FROM APTaskTemplate__c WHERE Action_Plan__c =: apId];
        apTasksJSON = '[{"Id":"'+ aptInserted.id + '","Task_Number__c":230,' +
                '"Subject__c":"Avstemming a-melding (skyldig skatt/aga terminvis)",' +
                '"Frequency__c":"Bi-monthly","Reminder__c":true,"ActionPlanTemplate__c":"'+ tempId + '",' +
                '"Assigned_Role__c":"Payroll Officer","User__c":"'+ userId + '","taskIndex__c":0,' +
                '"IsMandatory__c":true,"Skip_Weekends__c":false,"IsVisible__c":true,' +
                '"Period_1__c":"2019-09-08","Period_2__c":"2019-09-08",'+
                '"AttachmentHeader__c":"'+ attHeaderId + '"}]';
        //Update
        AptActionPlanController.savePlan(apId, apTasksJSON, delTasksJSON,
                contractId, fiscalYear, planName, skipWeekend);

        APTaskTemplate__c apTaskTemplate = [
                SELECT
                        Action_Plan__c,
                        ActionPlanTemplate__c,
                        Assigned_Role__c,
                        Assigned_Type__c,
                        Attachment_Status__c,
                        AttachmentHeader__c,
                        Comments__c,
                        Contact__c,
                        CreatedById,
                        CreatedDate,
                        Frequency__c,
                        Id,
                        IsDeleted,
                        IsMandatory__c,
                        IsVisible__c,
                        LastActivityDate,
                        LastModifiedById,
                        LastModifiedDate,
                        Minutes_Reminder__c,
                        Name,
                        Period_10__c,
                        Period_11__c,
                        Period_12__c,
                        Period_1__c,
                        Period_2__c,
                        Period_3__c,
                        Period_4__c,
                        Period_5__c,
                        Period_6__c,
                        Period_7__c,
                        Period_8__c,
                        Period_9__c,
                        Reminder__c,
                        SendEmail__c,
                        Skip_Weekends__c,
                        Status__c,
                        Subject__c,
                        SystemModstamp,
                        Task_Number__c,
                        TaskId__c,
                        taskIndex__c,
                        TemplateStaticPeriodDates__c,
                        TemplateStaticPeriods__c,
                        User__c
                FROM APTaskTemplate__c WHERE Action_Plan__c =: ap.id];
        apTasksJSON = '[]';
        List<APTaskTemplate__c> apTaskTemplates = new List<APTaskTemplate__c>();
        System.debug(apTaskTemplate.AttachmentHeader__c);

        apTaskTemplates.add(apTaskTemplate);
        delTasksJSON = JSON.serialize(apTaskTemplates);

        //Delete
        AptActionPlanController.savePlan(apId, apTasksJSON, delTasksJSON,
                contractId, fiscalYear, planName, skipWeekend);

        ActionPlan__c actionPlan = [SELECT id FROM ActionPlan__c];
        delete actionPlan;
        Test.stopTest();
    }
}