force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account_Owner_KA__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_KA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kundeansvarlig</inlineHelpText>
    <label>Account Owner (KA)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Kontrakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AptActionPlanCreationBatchTest.cls
/**
 * Created by jozef on 18. 5. 2023.
 */

@IsTest
private class AptActionPlanCreationBatchTest {
    @TestSetup static void setup() {
        AptUtilDataTest.setup();
    }
    @IsTest
    static void testBehavior() {
        AptUtilDataTest.createActionPlanTasks(2);
        Contract__c con = [SELECT id, Account_Owner_KA__c FROM Contract__c LIMIT 1];
        con.Account_Owner_KA__c = UserInfo.getUserId();
        update con;
        Test.StartTest();
        AptActionPlanCreationBatch creationBatch = new AptActionPlanCreationBatch();
        ID batchprocessid = Database.executeBatch(creationBatch);
        Test.StopTest();
    }

    @IsTest
    static void testFailBehavior() {
        AptUtilDataTest.createActionPlanTasks(5000);
        Test.StartTest();
        AptActionPlanCreationBatch creationBatch = new AptActionPlanCreationBatch();
        ID batchprocessid = Database.executeBatch(creationBatch);
        Test.StopTest();
    }

    @IsTest
    static void testFiscalYearBehavior() {
        AptUtilDataTest.createActionPlanTasks(2);
        Contract__c con = [SELECT id, Account_Owner_KA__c FROM Contract__c LIMIT 1];
        con.Account_Owner_KA__c = UserInfo.getUserId();
        update con;
        Integer fiscalYear = System.today().year() + 1;
        Test.StartTest();
        AptActionPlanCreationBatch creationBatch = new AptActionPlanCreationBatch(fiscalYear);
        ID batchprocessid = Database.executeBatch(creationBatch);
        Test.StopTest();
    }
}