force-app/main/default/objects/Account/fields/Accountec_UUID__c.field-meta.xml
<CustomField>
    <fullName>Accountec_UUID__c</fullName>
    <label>Accountec UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Accounting_Channel_URL__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Channel_URL__c</fullName>
    <label>Accounting Channel URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country2__c.field-meta.xml
<CustomField>
    <fullName>Country2__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Payroll_Channel_URL__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Channel_URL__c</fullName>
    <label>Payroll Channel URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SiteURL__c.field-meta.xml
<CustomField>
    <fullName>SiteURL__c</fullName>
    <label>SiteURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountecCreateQueueable.cls
global class AccountecCreateQueueable implements Queueable , Database.AllowsCallouts {
	
	Map<Id, SObject> accountNewMAP = new Map<Id, SObject>();
    Map<Id, SObject> accountOldMAP = new Map<Id, SObject>();
    
    global AccountecCreateQueueable(Map<Id, SObject> accountCLSNewMap,Map<Id, SObject> accountCLSOldMap)
    {
        this.accountNewMAP = accountCLSNewMap;
        this.accountOldMAP = accountCLSOldMap;
    }
    
    global void execute(QueueableContext context) 
    {
        for( Id accId : accountNewMAP.keySet() )
        {
            Account newAccount = (Account)accountNewMAP.get(accId);
            Account oldAccount = (Account)accountOldMAP.get(accId);
            
            if( newAccount.Country2__c == 'SE - Sweden' && newAccount.SiteURL__c !=NULL && newAccount.Accounting_Channel_URL__c !=NULL && newAccount.Payroll_Channel_URL__c !=NULL && newAccount.Accountec_UUID__c !=NULL  && oldAccount.SiteURL__c != newAccount.SiteURL__c )
            {
              //  AccountechAPICallout.makeCallout();
            } 
        }
    }
}