force-app/main/default/objects/Account/fields/Accountec_UUID__c.field-meta.xml
<CustomField>
    <fullName>Accountec_UUID__c</fullName>
    <label>Accountec UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Accounting_Channel_URL__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Channel_URL__c</fullName>
    <label>Accounting Channel URL</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CreateCalloutAPI__c.field-meta.xml
<CustomField>
    <fullName>CreateCalloutAPI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CreateCalloutAPI</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Field_UUID__c.field-meta.xml
<CustomField>
    <fullName>Field_UUID__c</fullName>
    <label>Field UUID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SiteURL__c.field-meta.xml
<CustomField>
    <fullName>SiteURL__c</fullName>
    <label>SiteURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SPGroupID__c.field-meta.xml
<CustomField>
    <fullName>SPGroupID__c</fullName>
    <label>SPGroupID</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APIAccountec__c/APIAccountec__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>APIAccountec</label>
</CustomObject>

force-app/main/default/classes/CreateAccountecUpdateField.cls
public class CreateAccountecUpdateField {
    
    //callout from create function to update field
    public static void updatefield(string ac,string UUID,string methodtype)
    {	try
      {
        Account acc = (Account)JSON.deserialize(ac, Account.class);
        string newAccessToken = AccountechAPICallout.RefreshToken();
        
        system.debug('INSIDE UPDATE FROM CREATE FUNCTION');
        APIAccountec__c act = APIAccountec__c.getValues('Accountec Credentials');
        string BaseURL = act.BaseURL__c;
        string Secret = act.Secret__c;
        Map<String, Object> requestBody = new Map<String, Object>();
        requestBody.put('field','Other');
        requestBody.put('value',acc.SiteURL__c+acc.Accounting_Channel_URL__c+'*'+acc.SPGroupID__c);
        
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(BaseURL+'/clients/'+UUID+'/fields');
        System.debug('Update field:->'+ UUID);
        request.setHeader('Client-Secret',Secret);
        request.setHeader('Content-Type','application/json');  
        request.setHeader('Authorization','Bearer '+newAccessToken); 
        system.debug('Serialize req body for UPDATE from create-> '+JSON.serialize(requestBody));
        
        request.setBody(JSON.serialize(requestBody));
        
        request.setMethod(methodtype);
        
        HttpResponse response = http.send(request);
        
        system.debug('**Response for update from create->'+response);
        system.debug('**Response body for update from create->'+response.getbody());
        if(string.isNotEmpty(response.getbody())) 
        {
            {
                Map<String, Object> ResponsefromAccountecforUpdateAPI = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
                system.debug('Response for UPDATE API from create'+ResponsefromAccountecforUpdateAPI);
                
                if(response.getStatusCode() == 201 || response.getStatusCode() == 200)
                {   
                    string  fieldUUID = (string)ResponsefromAccountecforUpdateAPI.get('uuid');
                    system.debug('field UUID->'+fieldUUID);
                    List<Account> aclist= new List<Account>();
                    Account a =new Account();
                    a.id = acc.id; 
                    a.Accountec_UUID__c = UUID;
                    a.Field_UUID__c = fieldUUID;
                    a.CreateCalloutAPI__c = true;
                    aclist.add(a);
                    system.debug('list to Update customer from create->'+aclist);
                    Database.update(aclist,true); 
                }
                else
                {
                    system.debug('status code not 200 for update API from create');
                }
                
            }
        }
    }
     catch(Exception e)
     {
         system.debug('An exception occurred in Update Field from Create: ' + e.getMessage());
     }
    }
}