force-app/main/default/objects/Account/fields/Assignment_Responsible__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Authorized Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_AR_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to bypass validation rule in process builder process for updating Oppdragsansvarlig and Account Owner (KA)</description>
    <label>Bypass Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Case_Invoicable_Flow__c.field-meta.xml
<CustomField>
    <fullName>Case_Invoicable_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Not in use, to be deleted.</description>
    <label>Case Invoicable (Case Flow)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Contract_Start_Date_Oper__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date_Oper__c</fullName>
    <description>Used in XLedger integration Not used</description>
    <label>Contract Start Date (Oper.)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cost_Center__c.field-meta.xml
<CustomField>
    <fullName>Cost_Center__c</fullName>
    <label>Cost Center</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country2__c.field-meta.xml
<CustomField>
    <fullName>Country2__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Create_Case__c.field-meta.xml
<CustomField>
    <fullName>Create_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox used to trigger process to create Case records.</description>
    <label>Create Case</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Create_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Create_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox used to trigger process to create Opportunity records.</description>
    <label>Create Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Group__c.field-meta.xml
<CustomField>
    <fullName>Customer_Group__c</fullName>
    <inlineHelpText>Kundegruppe</inlineHelpText>
    <label>Customer Group</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/DESKSCMT__Desk_Migrated_Account__c.field-meta.xml
<CustomField>
    <fullName>DESKSCMT__Desk_Migrated_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Desk Migrated Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Firm__c.field-meta.xml
<CustomField>
    <fullName>Firm__c</fullName>
    <label>Firm</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>View Ledger AB</fullName>
                <label>VIEW Ledger AB</label>
            </value>
            <value>
                <fullName>View Ledger AS</fullName>
                <label>VIEW Ledger AS</label>
            </value>
            <value>
                <fullName>View Maritime AS</fullName>
                <label>VIEW Maritime AS</label>
            </value>
            <value>
                <fullName>View Tax AS</fullName>
                <label>VIEW Tax AS</label>
            </value>
            <value>
                <fullName>VIEW Construct AS</fullName>
            </value>
            <value>
                <fullName>VIEW Procurator AS</fullName>
            </value>
            <value>
                <fullName>View Ledger Sandefjord AS</fullName>
                <isActive>false</isActive>
                <label>VIEW Ledger Sandefjord AS</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inspection_on_money_laundering_completed__c.field-meta.xml
<CustomField>
    <fullName>Inspection_on_money_laundering_completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inspection on money laundering completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Delivery_Method__c</fullName>
    <inlineHelpText>Fakturaforsendelse</inlineHelpText>
    <label>Invoice Delivery Method</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Late_payment__c.field-meta.xml
<CustomField>
    <fullName>Late_payment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Late payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <label>Payment</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Price_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Price_Agreement__c</fullName>
    <inlineHelpText>Avtaletype</inlineHelpText>
    <label>Price Agreement</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Project_Number_Operational__c.field-meta.xml
<CustomField>
    <fullName>Project_Number_Operational__c</fullName>
    <description>Updated by Project Flow</description>
    <label>Project Number - Operational</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Support_Agreement__c</fullName>
    <label>Support Agreement</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Price_Agreement_Setting__c/Activity_Price_Agreement_Setting__c.object-meta.xml
<CustomObject>
    <label>Activity Price Agreement Setting</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Price Agreement Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Price_Agreement_Setting__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Price_Agreement_Setting__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Price_Agreement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Price_Agreement_Setting__c/fields/Price_Agreement_Field__c.field-meta.xml
<CustomField>
    <fullName>Price_Agreement_Field__c</fullName>
    <label>Price Agreement Field</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting</fullName>
                <isActive>false</isActive>
                <label>Accounting</label>
            </value>
            <value>
                <fullName>Consulting</fullName>
                <isActive>false</isActive>
                <label>Consulting</label>
            </value>
            <value>
                <fullName>PA_Accounting__c</fullName>
            </value>
            <value>
                <fullName>PA_Consulting__c</fullName>
                <isActive>false</isActive>
                <label>PA_Consulting__c</label>
            </value>
            <value>
                <fullName>PA_HR__c</fullName>
                <isActive>false</isActive>
                <label>PA_HR__c</label>
            </value>
            <value>
                <fullName>PA_Payroll__c</fullName>
            </value>
            <value>
                <fullName>PA_Reporting__c</fullName>
            </value>
            <value>
                <fullName>PA_Services__c</fullName>
            </value>
            <value>
                <fullName>PA_Support__c</fullName>
            </value>
            <value>
                <fullName>PA_VTI__c</fullName>
            </value>
            <value>
                <fullName>PA_Year_end_reporting__c</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
                <isActive>false</isActive>
                <label>Payroll</label>
            </value>
            <value>
                <fullName>VTI</fullName>
                <isActive>false</isActive>
                <label>VTI</label>
            </value>
            <value>
                <fullName>Year end reporting</fullName>
                <isActive>false</isActive>
                <label>Year end reporting</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Price_Agreement_Setting__c/fields/Value_not_allowed__c.field-meta.xml
<CustomField>
    <fullName>Value_not_allowed__c</fullName>
    <label>Value not allowed</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Activity_Price_Agreement</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project data for time charging App</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Number__c.field-meta.xml
<CustomField>
    <fullName>Project_Number__c</fullName>
    <label>Project Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Operational.recordType-meta.xml
<RecordType>
    <fullName>Operational</fullName>
    <active>true</active>
    <description>Ongoing Operations Project - When creating this Project type you will also automatically create a related Project Task. Names for both Project and Project Task will automatically be updated upon saving.</description>
    <label>Operational</label>
</RecordType>

force-app/main/default/objects/Project_Number_o__c/Project_Number_o__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Project Number</label>
</CustomObject>

force-app/main/default/objects/Project_Number_o__c/fields/Identifier__c.field-meta.xml
<CustomField>
    <fullName>Identifier__c</fullName>
    <label>Identifier</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Number_o__c/fields/Project_Number_Operational__c.field-meta.xml
<CustomField>
    <fullName>Project_Number_Operational__c</fullName>
    <label>Project Number - Operational</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project_task__c/Project_task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <description>An entry of project time in the timekeeping system</description>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_Activity__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Activity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TimekeepingCalendarTest.cls
/**
 * @author Jozef 
 * @date 24.3.2021.
 * @description //TODO
 */

@IsTest
private class TimekeepingCalendarTest {
    @TestSetup
    static void setup(){
        Activity_Price_Agreement_Setting__c settings = new Activity_Price_Agreement_Setting__c();
        settings.Activity__c = '0202 Periodic reconciliation';
        settings.Exception__c = 'Hourly Rate';
        settings.Price_Agreement_Field__c = 'PA_Accounting__c';
        settings.Value_not_allowed__c = 'Hourly Rate';
        insert settings;

        Project_Number_o__c pSetting = new Project_Number_o__c();
        pSetting.Identifier__c = 'PNO';
        pSetting.Project_Number_Operational__c = 1;
        insert pSetting;

        prepareProjectTasks();
    }


    static void prepareProjectTasks(){
        Account account = new Account(
                Name = 'Mørland Sko AS',            // Account Name
                //Type = 'Customer',                                    // Type
                Country2__c = 'NO - Norge',                          // Country

                Firm__c = 'VIEW Ledger AS',                           // Firm
                //Project_Number_Operational__c = '10148',              // Project Number - Operational
                Assignment_Responsible__c = UserInfo.getUserId(),
                Business_Area__c = '120 - Xledger - Tjeneste',
                Bypass_Validation_Rule__c = false,
                Case_Invoicable_Flow__c = false,
                Contract_Start_Date_Oper__c = System.today(),
                Cost_Center__c = '01 Oslo Felles',
                Create_Case__c = false,
                Create_Opportunity__c = false,
                Customer_Group__c = 'Premium',
                Deactivated__c = false,
                DESKSCMT__Desk_Migrated_Account__c = false,
                Inspection_on_money_laundering_completed__c = false,  // Inspection on money laundering completed
                Invoice_Delivery_Method__c = 'Internal',
                Late_payment__c = false,
                Payment__c = 'Invoice',
                Price_Agreement__c = 'Unit Price',
                Support_Agreement__c = '500 No Support',
                Type = 'Dummy'
        );
        insert account;
        RecordType rt = [SELECT id, DeveloperName FROM RecordType WHERE SobjectType = 'Project__c'
            AND DeveloperName = 'Operational'];

        Project__c proj = new Project__c(
                //Project_Number__c = 10148,
                Name = 'Test Project - 2021',         // Project Name
                RecordTypeId = rt.id,
                Account__c = account.id,              // Account
                Status__c = 'Draft',                         // Status
                Start_Date__c = System.today(),  // Start Date
                Invoice_Responsible__c = UserInfo.getUserId(),
                End_Date__c = System.today().addYears(1),    // End Date
                Budgeting_Completed__c = false,
                Integrations__c = false
        );
        insert proj;

        Project_task__c projectTask = new Project_task__c();
        projectTask.Project__c = proj.id;
        projectTask.Status__c = 'Ongoing';
        projectTask.Default_Time_Type__c = '0 Normal Time';
        projectTask.Resource__c = UserInfo.getUserId();
        insert projectTask;
    }

    @IsTest
    static void getActivityPriceAgreementConfigTest() {
        TimekeepingCalendar.getActivityPriceAgreementConfig();
    }

    @IsTest
    static void getActivityPriceAgreementOptionsTest() {
        List<Project_task__c> projectTasks = [SELECT id FROM Project_task__c];
        List<String> pTasks = new List<String>();
        for (Project_task__c pt : projectTasks) {
            pTasks.add(pt.id);
        }
        TimekeepingCalendar.getActivityPriceAgreementOptions(pTasks);
    }

    @IsTest
    static void testBehaviour() {
        List<Time__c> times = new List<Time__c>();
        Time__c t = new Time__c();
        List<Project_task__c> projectTasks = [SELECT id FROM Project_task__c];

        t.Date__c = System.today();
        t.Project_Task__c = projectTasks.get(0).Id;
        t.Incurred_By__c = UserInfo.getUserId();
        t.Registered_Hours__c = 2;
        t.Registered_Minutes__c = 0;
        t.Billable_Hours__c = 2;
        t.Billable_Minutes__c = 0;
        t.Description__c = 'Description';
        t.Main_Activity__c = 'Accounting (NOR)';
        t.Activity__c = '0201 Vouchers';
        t.Time_Type__c = '0 Normal Time';
        t.Comment__c = 'Comment';
        t.Activity_Price_Agreement__c = 'Hourly Rate';
        t.Project_Country__c = 'NO - Norge';
        //insert t;

        times.add(t);

        TimekeepingCalendar.saveTime(times);

        String timeid = t.id;
        String timedate = '2021-04-07T00:00:00';
        try {
            TimekeepingCalendar.updateTime(timeid, timedate);
        }catch (Exception ex){

        }
        TimekeepingCalendar.getAllTimes();
        TimekeepingCalendar.getCurrentUser();
        TimekeepingCalendar.getMainActivityValues();
        TimekeepingCalendar.getActivityValues('Accounting');
        /* Time Type remove */
        TimekeepingCalendar.getTimeTypeValues();
        TimekeepingCalendar.getDefaultTimeTypeValue();

        TimekeepingCalendar.getProjTasks('', false, false);
        TimekeepingCalendar.getProjTasks('abc', true, true);
        TimekeepingCalendar.getProjTasks('abc', true, false);
        TimekeepingCalendar.getProjTasks('abc', false, true);
        TimekeepingCalendar.getProjectTaskCountry(t.Project_Task__c);
        TimekeepingCalendar.getMainPriceAgreement(t.Project_Task__c);
        TimekeepingCalendar.setUiConf(true, true);
        TimekeepingCalendar.setUiConf(false, false);
        TimekeepingCalendar.setUiConf(false, true);
        TimekeepingCalendar.setUiConf(true, false);
    }
}