force-app/main/default/objects/Account/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Billing Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If billing to another account than current</inlineHelpText>
    <label>Billing Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements (Billing Account)</relationshipLabel>
    <relationshipName>Agreements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptKontraktTriggerHandlerTest.cls
/**
 * @author Jozef 
 * @date 12.9.2019.
 * @description //TODO
 */

@IsTest
private class AptKontraktTriggerHandlerTest {
    @testSetup static void setup() {
        AptUtilDataTest.setup();
    }

    @IsTest
    static void insertKontrakt() {
        Account acc  = AptUtilDataTest.createAccount('NO - Norge');
        Contract__c con = AptUtilDataTest.getContract(acc);
        con.Scope__c = null;
        Test.startTest();
       // Test.setMock(HttpCalloutMock.class, new AptContractTriggerHandlerMock.CreateTeamSiteHelper_Mock());
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        insert con;
        con = [SELECT Country__c, Scope__c FROM Contract__c WHERE id  =: con.id ];
        System.assertEquals('NO - Norge', con.Country__c);
        /*List<String> acctualScope = con.Scope__c.split(';');
        List<String> expectedScope = AptKontraktTriggerHandler.NO_SCOPE.split(';');
        for (String expected : expectedScope) {
            if (!acctualScope.contains(expected)){
                system.assert(false);
            }
        }*/
        Test.stopTest();
    }

    @IsTest
    static void updateKontrakt() {
        Account acc  = AptUtilDataTest.createAccount('NO - Norge');
        Contract__c con = AptUtilDataTest.getContract(acc);
        insert con;

        Account accSweden  = AptUtilDataTest.createAccount('SE - Sweden');

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        // OCT 09 2019 commeted by Binary republik 
        // Modification reason : Test fail due mock class overriding which not used.
       // Test.setMock(HttpCalloutMock.class, new AptContractTriggerHandlerMock.CreateTeamSiteHelper_Mock());
        con.Account__c = accSweden.id;
        con.Scope__c = 'Payroll';
        con.Billing_Account__c = acc.Id;
        //update con;
        con = [SELECT Country__c FROM Contract__c WHERE Id =: con.id];

        //System.assertEquals('SE - Sweden', con.Country__c);
        Test.stopTest();
    }
}