force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Billing Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team And Authorizations</relationshipLabel>
    <relationshipName>Account_Team_And_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlanTemplate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/APTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task detail</description>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>ActionPlan__c</referenceTo>
    <relationshipName>R00NR0000000VccFMAS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/ActionPlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>ActionPlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action plan template from which was task created in ActionPlan. Used to identify when task from various templates are in the ActionPlan (for example when ActionPlan is generated from Contract with predefined various templates using)</description>
    <label>AP Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/APT_Task__c.field-meta.xml
<CustomField>
    <fullName>APT_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APT Task</label>
    <referenceTo>APTTaskTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values in custom settings.</description>
    <label>Assigned Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Tertial</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_10__c.field-meta.xml
<CustomField>
    <fullName>Period_10__c</fullName>
    <label>Period 10</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_3__c.field-meta.xml
<CustomField>
    <fullName>Period_3__c</fullName>
    <label>Period 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period 6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_7__c.field-meta.xml
<CustomField>
    <fullName>Period_7__c</fullName>
    <label>Period 7</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Skip_Weekends__c.field-meta.xml
<CustomField>
    <fullName>Skip_Weekends__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Weekends</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reporting Date</fullName>
            </value>
            <value>
                <fullName>Payroll Date</fullName>
            </value>
            <value>
                <fullName>Year end reporting date</fullName>
            </value>
            <value>
                <fullName>Closing date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_11__c.field-meta.xml
<CustomField>
    <fullName>Period_11__c</fullName>
    <label>Period 11</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_12__c.field-meta.xml
<CustomField>
    <fullName>Period_12__c</fullName>
    <label>Period 12</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_1__c.field-meta.xml
<CustomField>
    <fullName>Period_1__c</fullName>
    <label>Period 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_2__c.field-meta.xml
<CustomField>
    <fullName>Period_2__c</fullName>
    <label>Period 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period  4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period  5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period  6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_8__c.field-meta.xml
<CustomField>
    <fullName>Period_8__c</fullName>
    <label>Period 8</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_9__c.field-meta.xml
<CustomField>
    <fullName>Period_9__c</fullName>
    <label>Period 9</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Plus_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plus Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptActionPlanSync.cls
/**
 * Created by jozef on 12. 5. 2023.
 */

public without sharing class AptActionPlanSync {
    public class AgreementException extends Exception{}
    public class UserRole{
        public Id userId {get; set;}
        public String assignedRole {get; set;}
        public UserRole(Id userId, String assignedRole){
            this.userId = userId;
            this.assignedRole = assignedRole;
        }
    }

    public class Apt{
        public APTaskTemplate__c apTaskTemplate {get; set;}
        public APTTaskTemplate__c aptt {get; set;}
        public Date iniDate {get; set;}
        public Integer plusDays {get; set;}
        public String frequency {get; set;}
        public List<Decimal> periods {get; set;}
        public Map<Integer, Task> periodTaskMap {get; set;}
        public Integer fiscalYear {get; set;}
        Integer staticPeriodWithYearPlusOne;
        Map<Integer, Date> staticPeriodDates;
        Map<Integer, Date> periodDates;
        List<Task> toInsertTasks;
        List<Task> toDeleteTasks;
        List<Task> toUpdateTasks;
        Id contractId;
        Id accountId;

        public Apt(Task task, Date initDate, Decimal plusDays,  String frequency,
                APTTaskTemplate__c aptt, Id contractId, Id accountId){
            periods = new List<Decimal>();
            this.iniDate = initDate;
            this.plusDays = Integer.valueOf(plusDays);
            this.frequency = frequency;
            this.aptt = aptt;
            this.periodTaskMap = new Map<Integer, Task>();
            this.fiscalYear = Integer.valueOf(task.AP_Task__r.Action_Plan__r.FiscalYear__c);
            toInsertTasks = new List<Task>();
            toDeleteTasks = new List<Task>();
            toUpdateTasks = new List<Task>();
            this.contractId = contractId;
            this.accountId = accountId;
        }

        private void setPeriodsFields() {
            staticPeriodDates = new Map<Integer, Date>();
            periodDates = new Map<Integer, Date>();
            for (Integer i = 1; i <= 12; i++) {
                staticPeriodDates.put(i,(Date)aptt.get('Period_'+i+ '__c'));
                periodDates.put(i,(Date)apTaskTemplate.get('Period_'+i+ '__c'));
            }
        }
        Boolean isTaskOpened(Integer period){
            Boolean isOpened = true;
            Task t = this.periodTaskMap.get(period);
            if (t!=null){
                isOpened = t.Status == 'Not Started' || t.Status == 'Open';
            }
            return isOpened;
        }
        private void calculate() {
            if (aptt.Plus_Days__c != null && aptt.Plus_Days__c != 0){
                iniDate = iniDate.addDays(Integer.valueOf(aptt.Plus_Days__c));
            }
            setPeriodsFields();
            setPeriodsByFrequency();
        }
        private void setPeriodsByFrequency(){
            this.setStaticPeriodWithYearPlusOne();
            if (frequency == 'Monthly' || frequency == 'Månedlig'){
                this.setMonthly();
            }else if (frequency == 'Bi-monthly' || frequency == 'Terminvis'){
                this.setBiMonthly();
            }else if (frequency == 'Quarterly' || frequency == 'Kvartalsvis'){
                this.setQuarterly();
            }else if (frequency == 'Interim' || frequency == 'Tertial'){
                this.setInterim();
            }else if (frequency == 'Biannual' || frequency == 'Halvårlig'){
                this.setBiannual();
            }else if (frequency == 'Annual' || frequency == 'Årlig'){
                this.setAnnual();
            }
        }

        private void setMonthly(){
            setFrequency(1);
        }
        private void setBiMonthly(){
            setFrequency(2);
        }
        private void setQuarterly(){
            setFrequency(3);
        }
        private void setInterim(){
            setFrequency(4);
        }
        private void setBiannual(){
            setFrequency(6);
        }
        private void setAnnual(){
            Date iDate;
            Date staticDate = staticPeriodDates.get(12);
            if (staticDate == null){
                iDate = iniDate;
            }else{
                iDate = staticDate;
            }
            apTaskTemplate.Period_12__c = changeYear(iDate, fiscalYear + 1);
        }

        private void setFrequency(Integer modulo){
            Integer month = 0;
            Boolean incMonth = false;
            Boolean isDivisible = false;
            for (Integer i = 0; i <= 11; i++) {
                Integer period = i + 1;
                if (incMonth == true){
                    month = month + 1;
                }
                if (Math.mod(period, modulo) == 0) {
                    incMonth = true;
                    isDivisible = true;
                }else{
                    isDivisible = false;
                }
                if (isTaskOpened(period)){
                    setFrequencyForOpenedTasks(period, incMonth, month, isDivisible);
                }
            }
        }

        private void setFrequencyForOpenedTasks(Integer period, Boolean incMonth, Integer month,
                Boolean isDivisible){
            String periodField = 'Period_' + period + '__c';
            if (isDivisible == true) {
                setPeriodDate(periodField, month, period);
                incMonth = true;
            } else {
                Date periodDate = periodDates.get(period);
                if (periodDate != null && periodDate.year() != fiscalYear) {
                    periodDate = changeYear(periodDate, fiscalYear);
                    apTaskTemplate.put(periodField, periodDate);
                }
            }
            if (apTaskTemplate.Skip_Weekends__c == true){
                skipWeekend();
            }
            setStandardTasks(period, periodField);
        }

        private void setStandardTasks(Integer period, String periodField){
            Date periodDate = (Date)apTaskTemplate.get(periodField);
            Task t = periodTaskMap.get(period);
            if (t==null){
                if (periodDate!=null){
                    t = getNewStandardTask(period, periodDate);
                    toInsertTasks.add(t);
                }
            }else{
                if (periodDate == null){
                    toDeleteTasks.add(t);
                }else{
                    if (t.ActivityDate != periodDate){
                        t.ActivityDate = periodDate;
                        toUpdateTasks.add(t);
                    }
                }
            }
        }
        private Task getNewStandardTask(Integer period, Date periodDate){
            Task t = new Task();
            AptActionPlanUtil.setTask(t, periodDate, period, apTaskTemplate.Reminder__c );
            t.type = apTaskTemplate.ActionPlanTemplate__r.Name;
            t.Status = 'Not Started';
            AptActionPlanUtil.setTaskAccordingApt(t, apTaskTemplate, contractId, accountId);
            return t;
        }

        private void setPeriodDate(String periodField, Integer month, Integer period){
            Date staticDate = staticPeriodDates.get(period);
            if (staticDate == null){
                apTaskTemplate.put(periodField, addMonths(iniDate, month));
            }else{
                if (staticPeriodWithYearPlusOne == period){
                    apTaskTemplate.put(periodField, changeYear((Date)apTaskTemplate.get(periodField),
                            fiscalYear + 1));
                }else{
                    if (period == 12){
                        apTaskTemplate.put(periodField, changeYearStaticPeriod12((Date)apTaskTemplate.get(periodField),
                                fiscalYear));
                    }else{
                        apTaskTemplate.put(periodField, changeYear((Date)apTaskTemplate.get(periodField),
                                fiscalYear));
                    }
                }
            }
        }

        private Date changeYearStaticPeriod12(Date periodDate, Integer year){
            Integer month;
            Date newDate = null;
            if (periodDate != null){
                month = periodDate.month();
                if (month == 1 || month == 2 || month == 3 || month == 4){
                    year = year + 1;
                }
                newDate = Date.newInstance(year, month, periodDate.day());
            }
            return newDate;
        }
        private Date addMonths(Date inputDate, Integer months) {
            Date newDate;
            newDate = inputDate.addMonths(months);
            return newDate;
        }
        private Date changeYear(Date d, Integer year){
            Date newDate = null;
            if (d!=null) {
                newDate = Date.newInstance(year, d.month(), d.day());
            }
            return newDate;
        }

        private void setStaticPeriodWithYearPlusOne(){
            staticPeriodWithYearPlusOne = -1;
            Integer currentYear = -1;
            for (Integer i = 1; i <= 12; i++) {
                Date dt = staticPeriodDates.get(i);
                if (dt != null){
                    if (currentYear == -1){
                        currentYear = dt.year();
                    }else if (currentYear < dt.year()){
                        staticPeriodWithYearPlusOne = i;
                        break;
                    }
                }
            }
        }
        private void skipWeekend() {
            apTaskTemplate.Period_1__c = getWorkingDay(apTaskTemplate.Period_1__c);
            apTaskTemplate.Period_2__c = getWorkingDay(apTaskTemplate.Period_2__c);
            apTaskTemplate.Period_3__c = getWorkingDay(apTaskTemplate.Period_3__c);
            apTaskTemplate.Period_4__c = getWorkingDay(apTaskTemplate.Period_4__c);
            apTaskTemplate.Period_5__c = getWorkingDay(apTaskTemplate.Period_5__c);
            apTaskTemplate.Period_6__c = getWorkingDay(apTaskTemplate.Period_6__c);
            apTaskTemplate.Period_7__c = getWorkingDay(apTaskTemplate.Period_7__c);
            apTaskTemplate.Period_8__c = getWorkingDay(apTaskTemplate.Period_8__c);
            apTaskTemplate.Period_9__c = getWorkingDay(apTaskTemplate.Period_9__c);
            apTaskTemplate.Period_10__c = getWorkingDay(apTaskTemplate.Period_10__c);
            apTaskTemplate.Period_11__c = getWorkingDay(apTaskTemplate.Period_11__c);
            apTaskTemplate.Period_12__c = getWorkingDay(apTaskTemplate.Period_12__c);
        }

        private Date getWorkingDay(Date periodDate){
            Date newDate;
            DateTime dt;
            String dayInWeek;
            if (periodDate!=null){
                dt = periodDate;
                dayInWeek = dt.format('u');
                if (dayInWeek == '6'){
                    newDate = periodDate.addDays(2);
                }else if (dayInWeek == '7'){
                    newDate = periodDate.addDays(1);
                } else {
                    newDate = periodDate;
                }
            }else{
                newDate = periodDate;
            }
            return newDate;
        }

    }
    public class AptTaskData {
        List<Contract__c> changedContracts;
        List<Task> tasks;
        List<APTaskTemplate__c> apTaskTemplates;
        Map<Id, Apt> apts;

        public AptTaskData(){
            changedContracts = new List<Contract__c>();
            tasks = new List<Task>();
            apTaskTemplates = new List<APTaskTemplate__c>();
            apts = new Map<Id, Apt>();
        }

        private void setTasks(){
            tasks = [ SELECT Account__c,  AccountId, Accounting_Upload__c, Action_Plan__c, Action_Plan_Task__c,
                    ActivityDate, AP_Task__c, Assigned_Role__c, Completed_date__c, CompletedDateTime,
                    Controlled_by__c, Country__c, Days_Overdue__c, Days_to_Completed__c,  Overdue_Reason__c,
                    OwnerId, Payroll_Upload__c, Period__c, Priority, Scope__c, Status, Subject, Task_Control__c,
                    Task_Control_Modified_Date__c, Task_Descripton__c, Task_Number__c, Task_sequence__c,
                    TaskSubtype, TaskTemplateId__c, Type, WhatCount, WhatId, WhoCount, WhoId,
                    AP_Task__r.APT_Task__r.Initial_Start_Date__c,
                    AP_Task__r.APT_Task__r.Frequency__c,
                    AP_Task__r.APT_Task__r.Plus_Days__c,
                    AP_Task__r.Action_Plan__r.Contract__r.Year_end_reporting_date__c,
                    AP_Task__r.APT_Task__r.Period_1__c,
                    AP_Task__r.APT_Task__r.Period_2__c,
                    AP_Task__r.APT_Task__r.Period_3__c,
                    AP_Task__r.APT_Task__r.Period_4__c,
                    AP_Task__r.APT_Task__r.Period_5__c,
                    AP_Task__r.APT_Task__r.Period_6__c,
                    AP_Task__r.APT_Task__r.Period_7__c,
                    AP_Task__r.APT_Task__r.Period_8__c,
                    AP_Task__r.APT_Task__r.Period_9__c,
                    AP_Task__r.APT_Task__r.Period_10__c,
                    AP_Task__r.APT_Task__r.Period_11__c,
                    AP_Task__r.APT_Task__r.Period_12__c,
                    AP_Task__r.APT_Task__r.Skip_Weekends__c,
                    AP_Task__r.Action_Plan__r.FiscalYear__c,
                    AP_Task__r.TemplateStaticPeriods__c,
                    AP_Task__r.Skip_Weekends__c
            FROM Task WHERE //(Status = 'Open' OR Status = 'Not Started')
                    AP_Task__r.APT_Task__r.Initial_Start_Date__c = 'Year end reporting date'
                    AND WhatId IN: changedContracts];
            for (Task task : tasks) {
                Apt apt = apts.get(task.AP_Task__c);
                if (apt == null){
                    apt = new Apt(task,
                            task.AP_Task__r.Action_Plan__r.Contract__r.Year_end_reporting_date__c,
                            task.AP_Task__r.APT_Task__r.Plus_Days__c,
                            task.AP_Task__r.APT_Task__r.Frequency__c,
                            task.AP_Task__r.APT_Task__r, task.WhatId, task.AccountId);
                    apts.put(task.AP_Task__c, apt);
                }
                apt.periods.add(task.Period__c);
                apt.periodTaskMap.put(Integer.valueOf(task.Period__c),task);
            }
        }
        private void setApTaskTemplates(){
            for (APTaskTemplate__c apTaskTemplate : [SELECT id,
                    Period_1__c,
                    Period_2__c, Period_3__c, Period_4__c, Period_5__c,
                    Period_6__c, Period_7__c, Period_8__c, Period_9__c, Period_10__c,
                    Period_11__c, Period_12__c, Skip_Weekends__c, Reminder__c, ActionPlanTemplate__r.Name,
                    Subject__c, Task_Number__c, IsMandatory__c, User__c, Comments__c, Description__c
            FROM APTaskTemplate__c WHERE id IN: apts.keySet()]) {
                Apt apt = apts.get(apTaskTemplate.id);
                apt.apTaskTemplate = apTaskTemplate;
            }
        }
        private void updateAptAndTasks() {
            setTasks();
            setApTaskTemplates();
            calculatePeriods();
            updateApTaskTemplates();
            updateStandardTasks();
        }

        private void updateStandardTasks() {
            List<Task> tasksToUpdate = new List<Task>();
            List<Task> tasksToInsert = new List<Task>();
            List<Task> tasksToDelete = new List<Task>();
            for (Apt apt : apts.values()) {
                tasksToDelete.addAll(apt.toDeleteTasks);
                tasksToUpdate.addAll(apt.toUpdateTasks);
                tasksToInsert.addAll(apt.toInsertTasks);
            }
            if (!tasksToDelete.isEmpty()){
                delete tasksToDelete;
            }
            if (!tasksToUpdate.isEmpty()){
                update tasksToUpdate;
            }
            if (!tasksToInsert.isEmpty()){
                insert tasksToInsert;
            }
        }

        private void updateApTaskTemplates() {
            if (!apTaskTemplates.isEmpty()){
                update apTaskTemplates;
            }
        }

        private void calculatePeriods() {
            for (Apt apt : apts.values()) {
                apt.calculate();
                apTaskTemplates.add(apt.apTaskTemplate);
            }
        }

        private void setContracts(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
            Contract__c newContract;
            Contract__c oldContract;
            for (Id id : newItems.keySet()) {
                newContract = (Contract__c)newItems.get(id);
                oldContract = (Contract__c)oldItems.get(id);
                if (newContract.Year_end_reporting_date__c != null
                        && (newContract.Year_end_reporting_date__c != oldContract.Year_end_reporting_date__c)){
                    changedContracts.add(newContract);
                }
            }
        }

    }

    public class ActionPlan {
        Map<ID, Map<String, Id>> contractAccountTeamMap;
        Map<Id, SObject> accountTeamAndAuthItems;
        List<APTaskTemplate__c> apTaskTemplatesToUpdate;
        Map<Id, UserRole> taskOwnerToUpdate;
        Map<ID , List<Task>> taskMap;
        List<Task> taskToUpdate;
        public ActionPlan(){
            accountTeamAndAuthItems = new Map<Id, SObject>();
            contractAccountTeamMap = new Map<ID, Map<String, Id>>();
            taskMap = new Map<ID , List<Task>>();
            apTaskTemplatesToUpdate = new List<APTaskTemplate__c>();
            taskToUpdate = new List<Task>();
            taskOwnerToUpdate = new Map<Id, UserRole>();
        }

        public void setContractAccountTeamMap(){
            for (SObject sobj : accountTeamAndAuthItems.values()) {
                Account_Team_And_Authorizations__c a = (Account_Team_And_Authorizations__c) sobj;
                if (a.Kontrakt__c != null) {
                    contractAccountTeamMap.put(a.Kontrakt__c, null);
                }
            }
            for (Account_Team_And_Authorizations__c a : [SELECT id, Kontrakt__c, Type__c, Responsible__c
            FROM Account_Team_And_Authorizations__c WHERE Kontrakt__c IN: contractAccountTeamMap.keySet()]){
                if (a.Kontrakt__c != null) {
                    Map<String, Id> accountTeamAndAuthorizationMap
                            = contractAccountTeamMap.get(a.Kontrakt__c);
                    if (accountTeamAndAuthorizationMap == null) {
                        accountTeamAndAuthorizationMap = new Map<String, Id>();
                        contractAccountTeamMap.put(a.Kontrakt__c, accountTeamAndAuthorizationMap);
                    }
                    accountTeamAndAuthorizationMap.put(a.Type__c, a.Responsible__c);
                }
            }
        }

        public void setTaskMap(){
            List<Task> tasks = [SELECT id, AP_Task__c, AP_Task__r.Action_Plan__r.Contract__c,
                    AP_Task__r.Action_Plan__r.Contract__r.Account_Owner_KA__c,
                    Assigned_Role__c, OwnerId
            FROM Task
            WHERE Status = 'Not Started'
            AND AP_Task__r.Action_Plan__r.Contract__c IN: contractAccountTeamMap.keySet()];
            for (Task t : tasks) {
                List<Task> taskList = taskMap.get(t.AP_Task__r.Action_Plan__r.Contract__c);
                if (taskList == null) {
                    taskList = new List<Task>();
                    taskMap.put(t.AP_Task__r.Action_Plan__r.Contract__c, taskList);
                }
                taskList.add(t);
            }
        }

        private Id getResponsible(Map<String, Id> allRoles, Task t){
            Id userId = null;
            if (!String.isEmpty(t.Assigned_Role__c)) {
                userId = allRoles.get(t.Assigned_Role__c);
            }
            return userId;
        }

        public void setTaskOwner() {
            for (List<Task> tasks : taskMap.values()) {
                for (Task t : tasks) {
                    Id originalUserId = t.OwnerId;
                    Map<String, Id> allRoles = contractAccountTeamMap.get(t.AP_Task__r.Action_Plan__r.Contract__c);
                    ID userId = getResponsible(allRoles, t);
                    String assignedRole;
                    if (userId == null){
                        assignedRole =  AptActionPlanController.ACCOUNT_OWNER;
                        t.OwnerId = t.AP_Task__r.Action_Plan__r.Contract__r.Account_Owner_KA__c;
                    }else{
                        assignedRole = t.Assigned_Role__c;
                        t.OwnerId = userId;
                    }
                    if (originalUserId != t.OwnerId) {
                        if (t.OwnerId == null) {
                            throw new AgreementException('Agreement is missing default Account Owner KA');
                        }
                        taskToUpdate.add(t);
                        taskOwnerToUpdate.put(t.AP_Task__c, new UserRole(t.OwnerId, assignedRole));
                    }
                }
            }
        }

        public void setApTaskUser() {
            apTaskTemplatesToUpdate = [SELECT id, User__c, Assigned_Role__c FROM APTaskTemplate__c
            WHERE Id IN: taskOwnerToUpdate.keySet()];
            for (APTaskTemplate__c apTask : apTaskTemplatesToUpdate) {
                AptActionPlanSync.UserRole ur = taskOwnerToUpdate.get(apTask.id);
                apTask.User__c = ur.userId;
                apTask.Assigned_Role__c = ur.assignedRole;
            }
        }


    }

    /*****************************************************
    * @description
        For all related Action Plans:
        Responsible__c
        Type__c
        According Type__c and related APTTemplateTask.Assigned_Role__c we do change of:
        APTTemplateTask.UserId = Responsible__c
        Taks.OwnerId = Responsible__c
    * @param  items
    */
    private static void synchronizeTaskOwners(Map<Id, SObject> items){
        ActionPlan actionPlan = new ActionPlan();
        actionPlan.accountTeamAndAuthItems = items;
        actionPlan.setContractAccountTeamMap();
        actionPlan.setTaskMap();
        actionPlan.setTaskOwner();
        actionPlan.setApTaskUser();
        if (!actionPlan.taskToUpdate.isEmpty()){
            update actionPlan.taskToUpdate;
            update actionPlan.apTaskTemplatesToUpdate;
        }
    }

    public static void synchronizeAccountTeamAfterInsert(Map<Id, SObject> newAccountTeamAndAuthItems) {
        synchronizeTaskOwners(newAccountTeamAndAuthItems);
    }

    public static void synchronizeAccountTeamAfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        synchronizeTaskOwners(newItems);
    }

    public static void synchronizeAccountTeamAfterDelete(Map<Id, SObject> oldItems) {
        synchronizeTaskOwners(oldItems);
    }

    public static void synchronizeActionPlan(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        synchronizeAptPeriods(newItems, oldItems);
    }

    private static void synchronizeAptPeriods(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {
        AptTaskData aptTaskData = new AptTaskData();
        aptTaskData.setContracts(newItems, oldItems);
        aptTaskData.updateAptAndTasks();
    }

}