force-app/main/default/objects/Account/fields/Country2__c.field-meta.xml
<CustomField>
    <fullName>Country2__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Billing Country</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NO - Norge</fullName>
                <label>NO - Norway</label>
            </value>
            <value>
                <fullName>SE - Sweden</fullName>
            </value>
            <value>
                <fullName>DK - Denmark</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptAccountTriggerHandler.cls
/**
 * @author Jozef 
 * @date 12.9.2019.
 * @description //TODO
 */

public with sharing class AptAccountTriggerHandler {

    public static void updateContractCountry(Map<Id, SObject> newItems, Map<Id, SObject> oldItems){
        Map<Id, String> accCountryMap = new Map<Id, String>();
        for (Id id : newItems.keySet()) {
            Account oldAccount = (Account)oldItems.get(id);
            Account newAccount = (Account)newItems.get(id);
            if (newAccount.Country2__c != oldAccount.Country2__c){
                accCountryMap.put(id, newAccount.Country2__c);
            }
        }
        List<Contract__c> contracts = [SELECT id, Country__c, Account__c FROM Contract__c
            WHERE Account__c IN : accCountryMap.keySet()];
        for (Contract__c contract : contracts) {
            contract.Country__c = accCountryMap.get(contract.Account__c);
        }
        if (!contracts.isEmpty()){
            update contracts;
        }
    }

}