force-app/main/default/objects/Account/fields/Deactivated__c.field-meta.xml
<CustomField>
    <fullName>Deactivated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action_Plan_Error__c/Action_Plan_Error__c.object-meta.xml
<CustomObject>
    <label>Action Plan Error</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Error Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Plan Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action_Plan_Error__c/fields/Child_Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Child_Job_Id__c</fullName>
    <label>Child Job Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Error__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action_Plan_Error__c/fields/Kontrakt__c.field-meta.xml
<CustomField>
    <fullName>Kontrakt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Errors_Action_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <defaultValue>Today()</defaultValue>
    <description>The Start Date of the Action Plan</description>
    <inlineHelpText>The Start Date of the Action Plan</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Account_Owner_KA__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_KA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kundeansvarlig</inlineHelpText>
    <label>Account Owner (KA)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Kontrakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Do_Not_Create_Action_Plan_Automatically__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Create_Action_Plan_Automatically__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Create Action Plan Automatically</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Fiscal_Year_End__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_End__c</fullName>
    <description>Used to show user what the end date is for the customers accounting year and secure correct planning.</description>
    <inlineHelpText>Used to show user what the end date is for the customers accounting year and secure correct planning.</inlineHelpText>
    <label>Fiscal Year End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/FiscalYearStart__c.field-meta.xml
<CustomField>
    <fullName>FiscalYearStart__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <label>Fiscal Year Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PayrollDate__c.field-meta.xml
<CustomField>
    <fullName>PayrollDate__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,15)</defaultValue>
    <label>Payroll Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ReportingDate__c.field-meta.xml
<CustomField>
    <fullName>ReportingDate__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,30)</defaultValue>
    <label>Reporting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ReportingFrequency__c.field-meta.xml
<CustomField>
    <fullName>ReportingFrequency__c</fullName>
    <defaultValue>&apos;Bi-monthly&apos;</defaultValue>
    <label>Reporting Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
                <default>true</default>
                <label>Bi-monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Tertial</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
                <isActive>false</isActive>
                <label>Interim</label>
            </value>
            <value>
                <fullName>Two-monthly</fullName>
                <isActive>false</isActive>
                <label>Two-monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Year_end_reporting_date__c.field-meta.xml
<CustomField>
    <fullName>Year_end_reporting_date__c</fullName>
    <label>Year end reporting date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/Operational.recordType-meta.xml
<RecordType>
    <fullName>Operational</fullName>
    <active>true</active>
    <label>Operational</label>
</RecordType>

force-app/main/default/classes/AptActionPlanCreationBatch.cls
/**
 * Created by jozef on 18. 5. 2023.
 */

public class AptActionPlanCreationBatch implements Database.Batchable<sObject>, Database.Stateful{
    public class LimitException extends Exception {}
    private String fiscalYear;
    private String currentYear;
    private Boolean isError;
    private Integer numRowsInOneTransaction;
    private Integer CustomFiscalYear;

    public static String allContractsQuery = 'SELECT id, Account__r.OwnerId, Name, OwnerId, Account__c, ' +
            'Account__r.Name, Scope__c, FiscalYearStart__c,  Account__r.Owner.IsActive, \n' +
            'StartDate__c, ReportingFrequency__c, PayrollDate__c, ReportingDate__c,\n' +
            'RecordType.Name, Account_Owner_KA__c, CloseDate__c,\n' +
            'Year_end_reporting_date__c, Fiscal_Year_End__c,\n' +
            '( SELECT id, FiscalYear__c FROM Action_Plans__r ' +
            'WHERE FiscalYear__c =: fiscalYear OR FiscalYear__c =: currentYear) ' +
            'FROM Contract__c ' +
            'WHERE Account__c != NULL ' +
            'AND Do_Not_Create_Action_Plan_Automatically__c = false ' +
            'AND Account__r.Deactivated__c = false ' +
            'AND RecordType.DeveloperName  = \'Operational\'';

    public Iterable<sObject> start(Database.BatchableContext param1) {
        if (customFiscalYear == null){
            Integer thisYear = System.today().year();
            currentYear = String.valueOf(thisYear);
            fiscalYear = String.valueOf(thisYear + 1);
        }else {
            currentYear = String.valueOf(customFiscalYear - 1);
            fiscalYear = String.valueOf(customFiscalYear);
        }
        return Database.query(allContractsQuery);
    }
    public AptActionPlanCreationBatch(Integer fiscalYear){
        this.customFiscalYear = fiscalYear;
        this.initialization();
    }

    public AptActionPlanCreationBatch(){
        this.customFiscalYear = null;
        this.initialization();
    }

    private void initialization(){
        isError = false;
        numRowsInOneTransaction = 0;
        removeErrorLog();
    }

    private void removeErrorLog() {
        delete [SELECT id FROM Action_Plan_Error__c];
    }

    public void execute(Database.BatchableContext param1, List<Contract__c> contracts) {
        numRowsInOneTransaction = 0;
        AptActionPlan aptActionPlan;
        List<Action_Plan_Error__c> errors = new List<Action_Plan_Error__c>();
        for (Contract__c contract : contracts) {
            if (isContractEligibleToHaveNewPlan(contract, currentYear)) {
                try {
                    aptActionPlan = new AptActionPlan(contract, fiscalYear);
                    aptActionPlan.prepare();
                    checkAmountOfInsertedRows(aptActionPlan);
                    aptActionPlan.create();
                }catch (Exception ex){
                    addError(param1, errors, contract, ex);
                }
            }
        }
        if (!errors.isEmpty()){
            writeError(errors);
        }
    }

    private void checkAmountOfInsertedRows(AptActionPlan aptActionPlan) {
        numRowsInOneTransaction = numRowsInOneTransaction + aptActionPlan.numberOfInsertedRows;
        if (numRowsInOneTransaction >= 10000){
            throw new LimitException('Decrease size of batch because you hit SF limit: Too many DML rows: 10001. ' +
                    'Number of records: ' + numRowsInOneTransaction);
        }
    }

    private void writeError(List<Action_Plan_Error__c> actionPlanErrors) {
        isError = true;
        insert actionPlanErrors;
    }

    private void addError(Database.BatchableContext param1, List<Action_Plan_Error__c> actionPlanErrors,
            Contract__c contract, Exception ex) {
        System.debug(ex.getStackTraceString());
        Action_Plan_Error__c error = new Action_Plan_Error__c();
        error.Kontrakt__c = contract.id;
        error.Cause__c = ex.getTypeName();
        error.Child_Job_Id__c = param1.getChildJobId();
        error.Job_Id__c = param1.getJobId();
        error.Fiscal_Year__c = fiscalYear;
        error.Message__c = getShort(ex.getMessage());
        error.StackTraceString__c = getShort(ex.getStackTraceString());
        actionPlanErrors.add(error);
    }

    public static Boolean isContractEligibleToHaveNewPlan(Contract__c contract,  String year){
        Boolean value = false;
        if (contract.Action_Plans__r.size() == 1 && contract.Action_Plans__r.get(0).FiscalYear__c == year){
            value = true;
        }
        return value;
    }

    private static String getShort(String text){
        String shortText = text;
        if (!String.isEmpty(text)) {
            shortText = text.left(131071);
        }
        return shortText;
    }

    public void finish(Database.BatchableContext param1) {
        if (isError == true){
            sendErrorEmail();
        }
    }
    private void sendErrorEmail() {
        String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'renate.slinning@viewledger.com'};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Automatic Action Plan Creation Error');
        string body = 'Hi,\n'+
                'there was an issue during automatic creation of Action Plans.\n ' +
                'You can check issue in Error Log: \n' +
                + sfdcBaseURL +'/lightning/o/Action_Plan_Error__c/list?filterName=all';
        mail.setHtmlBody(body);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }

}