force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DependentPicklistTest.cls
/**
 * @author Jozef 
 * @date 9.9.2019.
 * @description DependentPicklistTest
 */

@IsTest
private class DependentPicklistTest {
    @isTest
    private static void getDependentPicklistValuesTest(){
        Test.startTest();
        Map<Object,List<String>> result =
                DependentPicklist.getDependentPicklistValues( Contract__c.Scope__c );
        System.debug(result);
        Test.stopTest();
    }


    @isTest
    private static void getDependentPicklistValuesByValueTest(){
        Test.startTest();
        List<String> result =
                DependentPicklist.getDependentPicklistValues( Account_Team_And_Authorizations__c.Type__c,
                        'Account Team');
        System.debug(result);
        Test.stopTest();
    }

    @isTest
    private static void getPicklistMapValueTest(){
        Test.startTest();
        DependentPicklist.getPicklistValueMap( Account_Team_And_Authorizations__c.Type__c);
        Test.stopTest();
    }

    @isTest
    private static void getPicklistMapApiTest(){
        Test.startTest();
        DependentPicklist.getPicklistApiMap( Account_Team_And_Authorizations__c.Type__c);
        Test.stopTest();
    }
}