force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team And Authorizations</relationshipLabel>
    <relationshipName>Account_Team_And_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActionPlan__c/ActionPlan__c.object-meta.xml
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlan__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>R00NR0000000VZZ8MAO</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Action Plans</relationshipLabel>
    <relationshipName>Action_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/FiscalYear__c.field-meta.xml
<CustomField>
    <fullName>FiscalYear__c</fullName>
    <label>Fiscal Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActionPlan__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll</fullName>
                <default>true</default>
                <label>Payroll</label>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/APTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task detail</description>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/fields/Action_Plan__c.field-meta.xml
<CustomField>
    <fullName>Action_Plan__c</fullName>
    <label>Action Plan</label>
    <referenceTo>ActionPlan__c</referenceTo>
    <relationshipName>R00NR0000000VccFMAS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/ActionPlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>ActionPlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action plan template from which was task created in ActionPlan. Used to identify when task from various templates are in the ActionPlan (for example when ActionPlan is generated from Contract with predefined various templates using)</description>
    <label>AP Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values in custom settings.</description>
    <label>Assigned Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/AttachmentHeader__c.field-meta.xml
<CustomField>
    <fullName>AttachmentHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AttachmentHeader</label>
    <referenceTo>AttachmentHeader__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Tertial</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_10__c.field-meta.xml
<CustomField>
    <fullName>Period_10__c</fullName>
    <label>Period 10</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_3__c.field-meta.xml
<CustomField>
    <fullName>Period_3__c</fullName>
    <label>Period 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period 6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_7__c.field-meta.xml
<CustomField>
    <fullName>Period_7__c</fullName>
    <label>Period 7</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/AttachmentHeader__c.field-meta.xml
<CustomField>
    <fullName>AttachmentHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AttachmentHeader</label>
    <referenceTo>AttachmentHeader__c</referenceTo>
    <relationshipLabel>APT Task Templates</relationshipLabel>
    <relationshipName>APT_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_11__c.field-meta.xml
<CustomField>
    <fullName>Period_11__c</fullName>
    <label>Period 11</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_12__c.field-meta.xml
<CustomField>
    <fullName>Period_12__c</fullName>
    <label>Period 12</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_1__c.field-meta.xml
<CustomField>
    <fullName>Period_1__c</fullName>
    <label>Period 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_2__c.field-meta.xml
<CustomField>
    <fullName>Period_2__c</fullName>
    <label>Period 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period  4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period  5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period  6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_8__c.field-meta.xml
<CustomField>
    <fullName>Period_8__c</fullName>
    <label>Period 8</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_9__c.field-meta.xml
<CustomField>
    <fullName>Period_9__c</fullName>
    <label>Period 9</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/recordTypes/Implementation.recordType-meta.xml
<RecordType>
    <fullName>Implementation</fullName>
    <active>true</active>
    <label>Implementation</label>
</RecordType>

force-app/main/default/objects/Contract__c/recordTypes/Operational.recordType-meta.xml
<RecordType>
    <fullName>Operational</fullName>
    <active>true</active>
    <label>Operational</label>
</RecordType>

force-app/main/default/classes/AptActionPlan.cls
/**
 * Created by jozef on 19. 5. 2023.
 */

public without sharing class AptActionPlan {
    private Contract__c contract;
    private String fiscalYear;
    private List<APTaskTemplate__c> apTaskTemplates;
    public List<APTaskTemplate__c> apTasksForInsert {get; set;}
    public Integer numberOfInsertedRows {get; set;}
    ActionPlan__c plan;


    public AptActionPlan(Contract__c contract, String fiscalYear) {
        this.contract = contract;
        this.fiscalYear = fiscalYear;
        this.apTaskTemplates = new List<APTaskTemplate__c>();
        this.apTasksForInsert = new List<APTaskTemplate__c>();
        this.numberOfInsertedRows = 0;
    }

    public void prepare() {
        apTaskTemplates = copyTasks(contract.Id, fiscalYear);
        this.numberOfInsertedRows = apTaskTemplates.size() + 1;
        prepareSave();
        this.numberOfInsertedRows = this.numberOfInsertedRows + apTasksForInsert.size();
        Integer countOfTasks = calculateNumberOfInsertedTasks();
        this.numberOfInsertedRows = this.numberOfInsertedRows + countOfTasks;
    }

    private Integer calculateNumberOfInsertedTasks() {
        Integer numOfTask = 0;
        for (APTaskTemplate__c apt : apTasksForInsert) {
            if (apt.Period_1__c!=null){
                numOfTask++;
            }
            if (apt.Period_2__c!=null){
                numOfTask++;
            }
            if (apt.Period_3__c!=null){
                numOfTask++;
            }
            if (apt.Period_4__c!=null){
                numOfTask++;
            }
            if (apt.Period_5__c!=null){
                numOfTask++;
            }
            if (apt.Period_6__c!=null){
                numOfTask++;
            }
            if (apt.Period_7__c!=null){
                numOfTask++;
            }
            if (apt.Period_8__c!=null){
                numOfTask++;
            }
            if (apt.Period_9__c!=null){
                numOfTask++;
            }
            if (apt.Period_10__c!=null){
                numOfTask++;
            }
            if (apt.Period_11__c!=null){
                numOfTask++;
            }
            if (apt.Period_12__c!=null){
                numOfTask++;
            }
        }
        return numOfTask;
    }

    public void create() {
        saveActionPlan();
    }

    private String getActionPlanName() {
        //CustomerName + Year + [Implementation/Operational]
        String apName;
        String customerName = getShortNameOfAccount(contract.Account__r.Name);
        apName = customerName + ' ' + fiscalYear + ' ' + contract.RecordType.Name;
        return apName;
    }
    private String getShortNameOfAccount(String aName) {
        String newName = aName;
        if (aName.length() >= 59) {
            newName = aName.substring(0, 56) + '...';
        }
        return newName;
    }

    private static void copyApt(APTaskTemplate__c aptt, List<AttachmentHeader__c> headers,
            List<APTaskTemplate__c> apTaskTemplatesNew){
        APTaskTemplate__c newTask = aptt.clone(false, false, false, false);
        newTask.Period_1__c = (newTask.Period_1__c != null) ? newTask.Period_1__c.addYears(1) : newTask.Period_1__c;
        newTask.Period_2__c = (newTask.Period_2__c != null) ? newTask.Period_2__c.addYears(1) : newTask.Period_2__c;
        newTask.Period_3__c = (newTask.Period_3__c != null) ? newTask.Period_3__c.addYears(1) : newTask.Period_3__c;
        newTask.Period_4__c = (newTask.Period_4__c != null) ? newTask.Period_4__c.addYears(1) : newTask.Period_4__c;
        newTask.Period_5__c = (newTask.Period_5__c != null) ? newTask.Period_5__c.addYears(1) : newTask.Period_5__c;
        newTask.Period_6__c = (newTask.Period_6__c != null) ? newTask.Period_6__c.addYears(1) : newTask.Period_6__c;
        newTask.Period_7__c = (newTask.Period_7__c != null) ? newTask.Period_7__c.addYears(1) : newTask.Period_7__c;
        newTask.Period_8__c = (newTask.Period_8__c != null) ? newTask.Period_8__c.addYears(1) : newTask.Period_8__c;
        newTask.Period_9__c = (newTask.Period_9__c != null) ? newTask.Period_9__c.addYears(1) : newTask.Period_9__c;
        newTask.Period_10__c = (newTask.Period_10__c != null) ? newTask.Period_10__c.addYears(1) : newTask.Period_10__c;
        newTask.Period_11__c = (newTask.Period_11__c != null) ? newTask.Period_11__c.addYears(1) : newTask.Period_11__c;
        newTask.Period_12__c = (newTask.Period_12__c != null) ? newTask.Period_12__c.addYears(1) : newTask.Period_12__c;
        AttachmentHeader__c attachmentHeader = new AttachmentHeader__c();
        headers.add(attachmentHeader);
        apTaskTemplatesNew.add(newTask);
    }

    public static List<APTaskTemplate__c> copyTasks(Id contractId, String fiscalYear) {
        ActionPlan__c actionPlan;
        Integer year = Integer.valueOf(fiscalYear) - 1;
        String yearS = String.valueOf(year);
        List<ActionPlan__c> actionPlans = [SELECT Id, Contract__r.Scope__c FROM ActionPlan__c
        WHERE Contract__c = :contractId
        AND FiscalYear__c = :yearS];
        String apId;
        if (actionPlans.size() > 0) {
            actionPlan = actionPlans.get(0);
            apId = actionPlan.Id;
        }
        System.debug('aptId = ' + apId);
        List<APTaskTemplate__c> apTaskTemplates = new List<APTaskTemplate__c>();
        List<APTaskTemplate__c> apTaskTemplatesNew = new List<APTaskTemplate__c>();
        List<AttachmentHeader__c> headers =  new List<AttachmentHeader__c>();

        Map<String, String> assignedRoleTranslationApi = DependentPicklist.getPicklistApiMap(
                Account_Team_And_Authorizations__c.Type__c);
        if (!String.isEmpty(apId)) {
            apTaskTemplates = [
                    SELECT id, Task_Number__c, Subject__c, Frequency__c,
                            Assigned_Role__c, Reminder__c, Action_Plan__c,
                            Period_1__c, Period_2__c, Period_3__c, Period_4__c, Period_5__c, Period_6__c,
                            Period_7__c, Period_8__c, Period_9__c, Period_10__c, Period_11__c, Period_12__c,
                            ActionPlanTemplate__c, ActionPlanTemplate__r.Name,
                            Contact__c, Contact__r.Name, User__c, User__r.Name, Comments__c, TaskIndex__c,
                            IsMandatory__c, TemplateStaticPeriods__c,
                            AttachmentHeader__c, IsVisible__c, Skip_Weekends__c,
                            Description__c, APT_Task__r.Initial_Start_Date__c, APT_Task__r.Plus_Days__c,
                            APT_Task__r.Action_Plan_Template__r.Name,
                            APT_Task__r.Action_Plan_Template__r.Library_Template__c
                    FROM APTaskTemplate__c
                    WHERE Action_Plan__c = :apId
                    ORDER BY TaskIndex__c asc
            ];
            for (APTaskTemplate__c aptt : apTaskTemplates) {
                if (actionPlan.Contract__r.Scope__c.contains(aptt.APT_Task__r.Action_Plan_Template__r.Name)
                        || aptt.APT_Task__r.Action_Plan_Template__r.Library_Template__c == true){
                    copyApt(aptt, headers, apTaskTemplatesNew);
                }
            }
        }
        if (!headers.isEmpty()){
            insert headers;
        }

        //There should be a bug because is not possible add variable myVariable dynamicaly in component controller
        //and expression then validate {!t.myVariable == true}
        //even it's possible read this expression {!t.myVariable} then
        Integer apI = 0;
        for (APTaskTemplate__c apTaskTemplate : apTaskTemplatesNew) {
            apTaskTemplate.IsVisible__c = true;
            if (apTaskTemplate.Assigned_Role__c != null) {
                apTaskTemplate.Assigned_Role__c = assignedRoleTranslationApi.get(
                        apTaskTemplate.Assigned_Role__c);
            }
            apTaskTemplate.AttachmentHeader__c = headers.get(apI).id;
            apI++;
        }
        return apTaskTemplatesNew;
    }

    public static List<APTaskTemplate__c> getTasks(Id apId) {
        List<APTaskTemplate__c> apTaskTemplates = new List<APTaskTemplate__c>();
        Map<String, String> assignedRoleTranslationApi = DependentPicklist.getPicklistApiMap(
                Account_Team_And_Authorizations__c.Type__c);
        if (!String.isEmpty(apId)) {
            apTaskTemplates = [
                    SELECT id, Task_Number__c, Subject__c, Frequency__c,
                            Assigned_Role__c, Reminder__c, Action_Plan__c,
                            Period_1__c, Period_2__c, Period_3__c, Period_4__c, Period_5__c, Period_6__c,
                            Period_7__c, Period_8__c, Period_9__c, Period_10__c, Period_11__c, Period_12__c,
                            ActionPlanTemplate__c, ActionPlanTemplate__r.Name,
                            Contact__c, Contact__r.Name, User__c, User__r.Name, Comments__c, TaskIndex__c,
                            IsMandatory__c, TemplateStaticPeriods__c,
                            AttachmentHeader__c, IsVisible__c, Skip_Weekends__c,
                            Description__c, APT_Task__r.Initial_Start_Date__c, APT_Task__r.Plus_Days__c
                    FROM APTaskTemplate__c
                    WHERE Action_Plan__c = :apId
                    ORDER BY Task_Number__c, TaskIndex__c asc
            ];
        }
        //There should be a bug because is not possible add variable myVariable dynamicaly in component controller
        //and expression then validate {!t.myVariable == true}
        //even it's possible read this expression {!t.myVariable} then
        for (APTaskTemplate__c apTaskTemplate : apTaskTemplates) {
            apTaskTemplate.IsVisible__c = true;
            if (apTaskTemplate.Assigned_Role__c != null) {
                apTaskTemplate.Assigned_Role__c = assignedRoleTranslationApi.get(
                        apTaskTemplate.Assigned_Role__c);
            }
        }
        return apTaskTemplates;
    }

    private void prepareSave() {
        apTasksForInsert = new List<APTaskTemplate__c>();

        plan = new ActionPlan__c();
        plan.Name = getActionPlanName();
        plan.Contract__c = contract.id;
        plan.Account__c = contract.Account__c;
        plan.FiscalYear__c = fiscalYear;
        plan.SkipWeekends__c = false;
        insert plan;

        Map<String, String> assignedRoleTranslationVal = DependentPicklist.getPicklistValueMap(
                Account_Team_And_Authorizations__c.Type__c);

        for (APTaskTemplate__c apTaskTemplate : apTaskTemplates) {
            if (apTaskTemplate.APT_Task__r != null) {
                apTaskTemplate.APT_Task__r = null;
            }
            apTaskTemplate.IsVisible__c = true;
            apTaskTemplate.User__r = null;
            if (apTaskTemplate.Assigned_Role__c != null) {
                apTaskTemplate.Assigned_Role__c = assignedRoleTranslationVal.get(
                        apTaskTemplate.Assigned_Role__c);
            }
            apTaskTemplate.Action_Plan__c = plan.id;
            apTasksForInsert.add(apTaskTemplate);
        }
    }
    private void saveActionPlan() {
        AptActionPlanUtil util;
        util = new AptActionPlanUtil(false);

        if (!apTasksForInsert.isEmpty()) {
            //System.debug(apTasksForInsert);
            insert apTasksForInsert;
        }

        List<APTaskTemplate__c> newTasks = getTasks(plan.id);
        util.generateActionPlans(newTasks, plan.id);
    }
}