force-app/main/default/objects/Account/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Account_Owner_KA__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_KA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kundeansvarlig</inlineHelpText>
    <label>Account Owner (KA)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Kontrakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Fiscal_Year_End__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_End__c</fullName>
    <description>Used to show user what the end date is for the customers accounting year and secure correct planning.</description>
    <inlineHelpText>Used to show user what the end date is for the customers accounting year and secure correct planning.</inlineHelpText>
    <label>Fiscal Year End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/FiscalYearStart__c.field-meta.xml
<CustomField>
    <fullName>FiscalYearStart__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,1)</defaultValue>
    <label>Fiscal Year Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PayrollDate__c.field-meta.xml
<CustomField>
    <fullName>PayrollDate__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,15)</defaultValue>
    <label>Payroll Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ReportingDate__c.field-meta.xml
<CustomField>
    <fullName>ReportingDate__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),1,30)</defaultValue>
    <label>Reporting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ReportingFrequency__c.field-meta.xml
<CustomField>
    <fullName>ReportingFrequency__c</fullName>
    <defaultValue>&apos;Bi-monthly&apos;</defaultValue>
    <label>Reporting Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
                <default>true</default>
                <label>Bi-monthly</label>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Tertial</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
                <isActive>false</isActive>
                <label>Interim</label>
            </value>
            <value>
                <fullName>Two-monthly</fullName>
                <isActive>false</isActive>
                <label>Two-monthly</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Year_end_reporting_date__c.field-meta.xml
<CustomField>
    <fullName>Year_end_reporting_date__c</fullName>
    <label>Year end reporting date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AptActionPlanTest.cls
/**
 * Created by jozef on 19. 5. 2023.
 */

@IsTest
private class AptActionPlanTest {
    @testSetup public static void setup() {
        AptUtilDataTest.setup();
    }
    @IsTest
    static void createTest() {
        AptUtilDataTest.createActionPlanTasks(2);
        Contract__c con = [SELECT id, Account_Owner_KA__c FROM Contract__c LIMIT 1];
        con.Account_Owner_KA__c = UserInfo.getUserId();
        update con;
        con = [SELECT id, Account__r.OwnerId, Name, OwnerId, Account__c,
            Account__r.Name, Scope__c, FiscalYearStart__c,
            StartDate__c, ReportingFrequency__c, PayrollDate__c, ReportingDate__c,
            RecordType.Name, Account_Owner_KA__c, CloseDate__c,
            Year_end_reporting_date__c, Fiscal_Year_End__c
            FROM Contract__c WHERE id =: con.id];
        String fiscalYear = String.valueOf(System.today().year() + 1);
        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new AptContractTriggerHandlerMock.CreateTeamSiteHelper_Mock());
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        AptActionPlan plan = new AptActionPlan(con, fiscalYear);
        plan.prepare();
        plan.create();
        Test.stopTest();
    }
}