force-app/main/default/objects/Account/fields/SPGroupID__c.field-meta.xml
<CustomField>
    <fullName>SPGroupID__c</fullName>
    <label>SPGroupID</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team And Authorizations</relationshipLabel>
    <relationshipName>Account_Team_And_Authorizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Kontrakt__c.field-meta.xml
<CustomField>
    <fullName>Kontrakt__c</fullName>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Oppdragsteam_Fullmakter</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oppdragsteam_Fullmakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Agreements</relationshipLabel>
    <relationshipName>Contracts1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccTeamAndAuthTriggerHandlerScheduleJob.cls
global class AccTeamAndAuthTriggerHandlerScheduleJob implements Schedulable{
    
    // Define variables to hold the list of records to process and the type of operation to perform
    list<Account_Team_And_Authorizations__c> accTeamAuthLst = new list<Account_Team_And_Authorizations__c>();
    private String operationType;
    
    // Constructor that takes the list of records to process and the operation type as parameters
    global AccTeamAndAuthTriggerHandlerScheduleJob(list<Account_Team_And_Authorizations__c> accTeamAuthLst, String operationType){
        // Set the class variables to the values passed in as parameters
        this.accTeamAuthLst = accTeamAuthLst;
        this.operationType = operationType;
        system.debug(' In scheduler Operation type-->'+ operationType);
        system.debug(' In scheduler lst sp Id-->'+ accTeamAuthLst[0].Kontrakt__r.Account__r.SPGroupID__c);
        system.debug('In scheduler Email-->'+accTeamAuthLst[0].Responsible__r.Email);
    }
    
     // Method that runs when the job is executed
    global void execute(SchedulableContext sc) {
        try {
            if(operationType == 'Insert'){
                AccTeamAndAuthTriggerHandlerQueueablecls Queue = new AccTeamAndAuthTriggerHandlerQueueablecls(accTeamAuthLst, operationType);
                ID jobID = System.enqueueJob(Queue);
             }
            else if(operationType == 'Delete'){
                AccTeamAndAuthDeleteQueueable Queue = new AccTeamAndAuthDeleteQueueable(accTeamAuthLst,operationType);
                ID jobID = System.enqueueJob(Queue);
             }
            // Abort the job once the job is queued
            System.abortJob(sc.getTriggerId());
        } catch(Exception ex) {
            // log the exception or send an email
            ContractTriggerhandler.sendErrorMail('Exception occurred while processing the schedule job', ex.getMessage(), 'EXC');
        }
    }
}