force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>InvoiceLine-{0000}</displayFormat>
        <label>Invoice Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Billable_Hours__c.field-meta.xml
<CustomField>
    <fullName>Billable_Hours__c</fullName>
    <label>Billable Hours</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Billable_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Minutes__c</fullName>
    <label>Billable Minutes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Comment</label>
    <length>50000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date Incurred</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Incurred_By__c.field-meta.xml
<CustomField>
    <fullName>Incurred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incurred By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Incurred_By_Text__c.field-meta.xml
<CustomField>
    <fullName>Incurred_By_Text__c</fullName>
    <label>Incurred By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Main_Activity__c.field-meta.xml
<CustomField>
    <fullName>Main_Activity__c</fullName>
    <label>Main Activity</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Project data for time charging App</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Deploy</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Operational with outstanding tasks</fullName>
            </value>
            <value>
                <fullName>Signed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Account Deactivated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_task__c/Project_task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/Time__c.object-meta.xml
<CustomObject>
    <description>An entry of project time in the timekeeping system</description>
    <label>Time</label>
    <nameField>
        <displayFormat>T-{000000}</displayFormat>
        <label>Time Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Main_Activity__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Activity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/Billable_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Billable_Minutes__c</fullName>
    <description>The number of registered minutes that are billable</description>
    <label>Billable Minutes</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <description>Comment regarding registered time.</description>
    <inlineHelpText>Comment regarding registered time.</inlineHelpText>
    <label>Internal comment</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Incurred_By__c.field-meta.xml
<CustomField>
    <fullName>Incurred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incurred By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Main_Activity__c.field-meta.xml
<CustomField>
    <fullName>Main_Activity__c</fullName>
    <label>Main Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Project_Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Main_Activity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Project Task Status is Completed!</errorMessage>
        <filterItems>
            <field>Project_task__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Completed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_task__c</referenceTo>
    <relationshipLabel>Time</relationshipLabel>
    <relationshipName>Time</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Sent For Approval</fullName>
                <isActive>false</isActive>
                <label>Sent For Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoiceController.cls
public class InvoiceController {
	
    @AuraEnabled
	public static InvoiceWrapper createInvoiceAndInvoiceLines(String projectId){
       	/*Boolean hasError = false;
        String message = '';
        List<Project_task__c> projectTasks = [Select id, Project__r.Name, (Select id, Billable_Hours__c, Billable_Minutes__c, Date__c, Incurred_By__r.Id, Incurred_By__r.Name, Main_Activity__c, Activity__c, Comment__c From Time__r Where Status__c = 'Approved') From Project_task__c Where Project__c = :projectId];
        List<Invoice_Line__c> invoiceLines = new List<Invoice_Line__c>();
        List<Time__c> times = new List<Time__c>();
        if (projectTasks.size()>0) {
            Invoice__c invoice = new Invoice__c(Project__c = projectId,
                                               Status__c = 'Draft',
                                               Name = projectTasks[0].Project__r.Name + '');
            try {
                insert invoice;
            } catch (Exception e) {
                hasError = true;
                message = 'Invoice  cannot be created. Please contact Administrator.';
            }
            
            for (Project_task__c pt : projectTasks) {
                for (Time__c t : pt.Time__r) {
                    invoiceLines.add(new Invoice_Line__c (Invoice__c = invoice.Id,
                                        Billable_Hours__c = t.Billable_Hours__c,
                                        Billable_Minutes__c = t.Billable_Minutes__c,
                                        Incurred_By__c = t.Incurred_By__r.Id,
                                        Incurred_By_Text__c = t.Incurred_By__r.Name,
                                        Activity__c = t.Activity__c,
                                        Comment__c = t.Comment__c,
                                        Date__c = t.Date__c,
                                        Main_Activity__c = t.Main_Activity__c
                                        )
                                      );
                   t.Status__c = 'Invoiced';
                   times.add(t);
                }
            }
            try {
                insert invoiceLines;
                update times;
                invoice.Status__c = 'Approved';
                update invoice;
            } catch (Exception e) {
                hasError = true;
                message = 'Invoice Lines cannot be created. Please contact Administrator.';
            }
            return new InvoiceWrapper(invoice.Id, message, hasError);
        } else {
            hasError = true;
            message = 'There is no Project Tasks';
            return new InvoiceWrapper(null, message, hasError);
        }*/
        return new InvoiceWrapper(null, null, false);
    }
    
    @AuraEnabled
	public static InvoiceWrapper createInvoiceAndInvoiceLinesRanges(String projectId, String startDate, String endDate){
       	Boolean hasError = false;
        String message = '';
        Date sDate = Date.valueOf(startDate);
        Date eDate = Date.valueOf(endDate);
        
        List<Project_task__c> projectTasks = [Select id, Project__r.Name, (Select id, Billable_Hours__c, Billable_Minutes__c, Date__c, Incurred_By__r.Id, Incurred_By__r.Name, Main_Activity__c, Activity__c, Comment__c From Time__r Where Status__c = 'Approved' AND Date__c>= :sDate AND  Date__c<=: eDate) From Project_task__c Where Project__c = :projectId];
        List<Invoice_Line__c> invoiceLines = new List<Invoice_Line__c>();
        List<Time__c> times = new List<Time__c>();
        if (projectTasks.size()>0) {
            Invoice__c invoice = new Invoice__c(Project__c = projectId,
                                               Status__c = 'Draft',
                                               Name = projectTasks[0].Project__r.Name + ' / ' + startDate + ' - '+ endDate);
            try {
                insert invoice;
            } catch (Exception e) {
                system.debug('ERROR: ' + e);
                hasError = true;
                message = 'Invoice cannot be created. Please contact Administrator. ' + e.getMessage();
            }
            
            for (Project_task__c pt : projectTasks) {
                for (Time__c t : pt.Time__r) {
                    invoiceLines.add(new Invoice_Line__c (Invoice__c = invoice.Id,
                                        Billable_Hours__c = t.Billable_Hours__c,
                                        Billable_Minutes__c = t.Billable_Minutes__c,
                                        Incurred_By__c = t.Incurred_By__r.Id,
                                        Incurred_By_Text__c = t.Incurred_By__r.Name,
                                        Activity__c = t.Activity__c,
                                        Comment__c = t.Comment__c,
                                        Date__c = t.Date__c,
                                        Main_Activity__c = t.Main_Activity__c
                                        )
                                      );
                   t.Status__c = 'Invoiced';
                   times.add(t);
                }
            }
            try {
                insert invoiceLines;
                update times;
                invoice.Status__c = 'Approved';
                update invoice;
            } catch (Exception e) {
                hasError = true;
                message = 'Invoice Lines cannot be created. Please contact Administrator. ' + e.getMessage();
            }
           
            return new InvoiceWrapper(invoice.Id, message, hasError);
        } else {
            hasError = true;
            message = 'There is no Project Tasks';
            return new InvoiceWrapper(null, message, hasError);
        }
    }
    
    @AuraEnabled
	public static TimeWrapper getInvoiceLines(String projectId, String startDate, String endDate){
        Date sDate = Date.valueOf(startDate);
        Date eDate = Date.valueOf(endDate);
       
        system.debug('StartDate 123: ' + sDate);
        List<Project_task__c> projectTasks = [Select id, (Select id, Billable_Hours__c, Billable_Minutes__c, Date__c, Incurred_By__r.Id, Incurred_By__r.Name, Main_Activity__c, Activity__c, Comment__c, Status__c From Time__r Where Date__c>= :sDate AND  Date__c<=: eDate) From Project_task__c Where Project__c = :projectId];
        List<Time__c> times = new List<Time__c>();
        List<Time__c> notApproved = new List<Time__c>();
        
        for (Project_task__c pt : projectTasks) {
            for (Time__c t : pt.Time__r) {
                if (t.Status__c == 'Approved') {
                   system.debug('Approved');
                   times.add(t); 
                } else if (t.Status__c != 'Invoiced')  {
                   notApproved.add(t);
                }
                
            }
        }
        return new TimeWrapper(times, notApproved.size());
    }
    @AuraEnabled
	public static String closeModal(){
        system.debug('CLOSE!');
        return null;
    }
    
    public class TimeWrapper {
    	@AuraEnabled
        public List<Time__c> times;
        
        @AuraEnabled
        public Integer notApproved;
        
        public TimeWrapper(List<Time__c> t, Integer nA) {
            times = t;
            notApproved = nA;
        }
    }
    public class InvoiceWrapper {
    	@AuraEnabled
        public String invoiceId;
        
        @AuraEnabled
        public String message;
        
        @AuraEnabled
        public Boolean hasError;
        
        public invoiceWrapper(String iId, String msg, Boolean hasErr) {
            invoiceId = iId;
            message = msg;
            hasError = hasErr;
        }
    }
}