force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlanTemplate__c/fields/Library_Template__c.field-meta.xml
<CustomField>
    <fullName>Library_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Library Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/fields/SkipDay__c.field-meta.xml
<CustomField>
    <fullName>SkipDay__c</fullName>
    <description>If a Due Date lands on a weekend it should be pushed to this day.</description>
    <label>Skip Day</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
                <default>true</default>
                <label>Monday</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/fields/SkipWeekends__c.field-meta.xml
<CustomField>
    <fullName>SkipWeekends__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
    <inlineHelpText>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</inlineHelpText>
    <label>Skip Weekends</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/AttachmentHeader__c.field-meta.xml
<CustomField>
    <fullName>AttachmentHeader__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AttachmentHeader</label>
    <referenceTo>AttachmentHeader__c</referenceTo>
    <relationshipLabel>APT Task Templates</relationshipLabel>
    <relationshipName>APT_Task_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reporting Date</fullName>
            </value>
            <value>
                <fullName>Payroll Date</fullName>
            </value>
            <value>
                <fullName>Year end reporting date</fullName>
            </value>
            <value>
                <fullName>Closing date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/IsMandatory__c.field-meta.xml
<CustomField>
    <fullName>IsMandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify mandatory task - if it is then removing from action is disabled.</description>
    <inlineHelpText>Is task mandatory?</inlineHelpText>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_11__c.field-meta.xml
<CustomField>
    <fullName>Period_11__c</fullName>
    <label>Period 11</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_12__c.field-meta.xml
<CustomField>
    <fullName>Period_12__c</fullName>
    <label>Period 12</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_1__c.field-meta.xml
<CustomField>
    <fullName>Period_1__c</fullName>
    <label>Period 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_2__c.field-meta.xml
<CustomField>
    <fullName>Period_2__c</fullName>
    <label>Period 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period  4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period  5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period  6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_8__c.field-meta.xml
<CustomField>
    <fullName>Period_8__c</fullName>
    <label>Period 8</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_9__c.field-meta.xml
<CustomField>
    <fullName>Period_9__c</fullName>
    <label>Period 9</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Plus_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plus Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>TaskId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00NR0000000Vd65MAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AttachmentHeader__c/AttachmentHeader__c.object-meta.xml
<CustomObject>
    <label>AttachmentHeader</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttachmentHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttachmentHeader__c/fields/AP_Task_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>AP_Task_Unique_Id__c</fullName>
    <label>AP Task Unique Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/CertifiedAccountant__c.field-meta.xml
<CustomField>
    <fullName>CertifiedAccountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certified Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/CustomerResponsibleAndRemittanceResp__c.field-meta.xml
<CustomField>
    <fullName>CustomerResponsibleAndRemittanceResp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account owner and Remittance Resp</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_1__c.field-meta.xml
<CustomField>
    <fullName>Employee_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_2__c.field-meta.xml
<CustomField>
    <fullName>Employee_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_3__c.field-meta.xml
<CustomField>
    <fullName>Employee_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Employee_4__c.field-meta.xml
<CustomField>
    <fullName>Employee_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee 4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/IntegrationResource__c.field-meta.xml
<CustomField>
    <fullName>IntegrationResource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Integration Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/PayrollOfficer__c.field-meta.xml
<CustomField>
    <fullName>PayrollOfficer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Officer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/ProjectManager__c.field-meta.xml
<CustomField>
    <fullName>ProjectManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contracts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AptTemplateController.cls
/**
 * @author Jozef
 * @date 18.2.2019.
 * @description //TODO
 */

public with sharing class AptTemplateController {

    @AuraEnabled
    public static List<APTTaskTemplate__c> getTasks(Id apId) {
        System.debug('aptId = ' + apId);
        List<APTTaskTemplate__c> aptTaskTemplates = new List<APTTaskTemplate__c>();
        try{
            Map<String, String> assignedRoleTranslationApi = DependentPicklist.getPicklistApiMap(
                    Account_Team_And_Authorizations__c.Type__c);
            if (!String.isEmpty(apId)) {
                aptTaskTemplates = [
                        SELECT id, Task_Number__c, Subject__c, Frequency__c,
                                Assigned_Role__c,  Reminder__c, User__c, User__r.Name, Comments__c, TaskIndex__c,
                                IsMandatory__c, Action_Plan_Template__c, AttachmentHeader__c, Skip_Weekends__c,
                                Period_1__c,  Period_2__c, Period_3__c,  Period_4__c,
                                Period_5__c,  Period_6__c, Period_7__c,  Period_8__c, Period_9__c,  Period_10__c,
                                Period_11__c, Period_12__c, Description__c, Initial_Start_Date__c,
                                Plus_Days__c
                        FROM APTTaskTemplate__c
                        WHERE Action_Plan_Template__c = :apId
                        ORDER BY TaskIndex__c asc
                ];

            }

            for (APTTaskTemplate__c aptTaskTemplate : aptTaskTemplates) {
                aptTaskTemplate.IsVisible__c = true;
                if (aptTaskTemplate.Assigned_Role__c != null) {
                    aptTaskTemplate.Assigned_Role__c = assignedRoleTranslationApi.get(
                            aptTaskTemplate.Assigned_Role__c);
                }
            }
        }catch (Exception ex){
            System.debug(ex.getStackTraceString());
            throw new AuraHandledException('AptTemplateController.getTasks : ' + ex.getMessage());
        }
        return aptTaskTemplates;
    }

    @AuraEnabled
    public static ActionPlanTemplate__c getTemplatePlan(Id recordId) {
        System.debug('recordId = ' + recordId);
        ActionPlanTemplate__c plan = new ActionPlanTemplate__c();
        if (!String.isEmpty(recordId)){
            List<ActionPlanTemplate__c> plans = [
                    SELECT Id, Name, Description__c, SkipWeekends__c, SkipDay__c, LastModifiedDate,
                            LastModifiedBy.Name, LastModifiedById, CreatedDate,
                            CreatedBy.Name, CreatedById, Owner.Name,
                            Library_Template__c, Start_Date__c
                    FROM ActionPlanTemplate__c
                    WHERE id =: recordId];
            if (!plans.isEmpty()){
                return plans.get(0);
            }else{
                throw new AuraHandledException('There is no record with id : ' + recordId);
            }
        }
        plan.Start_Date__c = null;
        return plan;
    }

    @AuraEnabled
    public static APTTaskTemplate__c getNewTemplatePlanTask(String index){
        //System.debug('getNewTemplateTask = ' + index);
        APTTaskTemplate__c at = new APTTaskTemplate__c();
        at.TaskIndex__c = Integer.valueOf(index);
        at.User__c = UserInfo.getUserId();
        at.IsVisible__c = true;

        AttachmentHeader__c attachmentHeader = new AttachmentHeader__c();
        attachmentHeader.AP_Task_Unique_Id__c = at.TaskId__c;
        insert attachmentHeader;

        at.AttachmentHeader__c = attachmentHeader.id;
        return at;
    }

    @AuraEnabled
    public static List<APTTaskTemplate__c> savePlan(Id tId, ActionPlanTemplate__c tPlan ,
            String tTasksJSON, String delTasksJSON) {

        System.debug('Save Plan id = ' + tId);
        System.debug('Save Plan data = ' + tPlan);
        System.debug('DELETE Tasks: ' + delTasksJSON);
        System.debug('UPDATE INSERT: ' + tTasksJSON);

        checkEditPermission();
        List<APTTaskTemplate__c> tTasks  = (List<APTTaskTemplate__c>) JSON.deserialize(tTasksJSON,
                List<APTTaskTemplate__c>.class);
        if(tTasks == null){
            throw new AuraHandledException('Impossible to retrieve the tasks list. Contact your system administrator');
        }

        List<APTTaskTemplate__c> delApTasks  = (List<APTTaskTemplate__c>) JSON.deserialize(delTasksJSON,
                List<APTTaskTemplate__c>.class);
        if(delApTasks == null){
            throw new AuraHandledException('Impossible to retrieve the tasks list for deletion. Contact your system administrator');
        }

        List<APTTaskTemplate__c> tTasksForDeletion = new List<APTTaskTemplate__c>();
        List<APTTaskTemplate__c> tTasksForInsert = new List<APTTaskTemplate__c>();
        List<APTTaskTemplate__c> tTasksForUpdate = new List<APTTaskTemplate__c>();
        List<AttachmentHeader__c> tAttHeadersForDeletion = new List<AttachmentHeader__c>();


        Set<ID> idTasksForDel = new Set<ID>();
        Set<ID> idAttForDel = new Set<ID>();
        for (APTTaskTemplate__c  t : delApTasks) {
            if (t.Id != null) {
                idTasksForDel.add(t.Id);
            }
            idAttForDel.add(t.AttachmentHeader__c);
        }

        if (!idTasksForDel.isEmpty()) {
            tTasksForDeletion = [SELECT Id FROM APTTaskTemplate__c WHERE Id IN:idTasksForDel];
            delete tTasksForDeletion;
        }

        if (!idAttForDel.isEmpty()) {
            tAttHeadersForDeletion = [SELECT Id FROM AttachmentHeader__c WHERE Id IN:idAttForDel];
            delete tAttHeadersForDeletion;
        }

        if (String.isEmpty(tId)){
            insert tPlan;
        }else {
            update tPlan;
        }

        Map<String, String> assignedRoleTranslationVal = DependentPicklist.getPicklistValueMap(
                Account_Team_And_Authorizations__c.Type__c);

        for (APTTaskTemplate__c tTaskTemplate : tTasks) {
            tTaskTemplate.IsVisible__c = true;
            tTaskTemplate.User__r = null;
            System.debug('ROLE:' + tTaskTemplate.Assigned_Role__c + ' : ' + assignedRoleTranslationVal);
            if (tTaskTemplate.Assigned_Role__c != null) {
                tTaskTemplate.Assigned_Role__c = assignedRoleTranslationVal.get(
                        tTaskTemplate.Assigned_Role__c);
            }
            if (tTaskTemplate.id == null){
                tTaskTemplate.Action_Plan_Template__c = tPlan.id;
                tTasksForInsert.add(tTaskTemplate);
            }else{
                tTasksForUpdate.add(tTaskTemplate);
            }
        }
        //TODO check which tasks has been changed
        if (!tTasksForUpdate.isEmpty()){
            update tTasksForUpdate;
        }

        if (!tTasksForInsert.isEmpty()) {
            System.debug(tTasksForInsert);
            insert tTasksForInsert;
        }

        List<APTTaskTemplate__c> newTasks = getTasks(tPlan.id);
        return newTasks;
    }

    private static void checkEditPermission(){
        String objectApiName = 'APTTaskTemplate__c';
        // Get the SObjectType for the object
        Schema.SObjectType objectType = Schema.getGlobalDescribe().get(objectApiName);
        // Get the DescribeSObjectResult for the object
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        // Check if the user has edit access on the object
        if (!objectDescribe.isUpdateable()) {
            System.debug('User does not have edit permission on ' + objectApiName);
            throw new AuraHandledException('You do not have permission to edit Action Plan Template.');
        }
    }

    @AuraEnabled
    public static List<String> fetchIniStartDatePicklistValues(){
        Map<String, String> initialStartDatePicklistMap = DependentPicklist.getPicklistValueMap(
                APTTaskTemplate__c.Initial_Start_Date__c);
        System.debug(initialStartDatePicklistMap);
        return initialStartDatePicklistMap.values();
    }

    @AuraEnabled
    public static List<String> fetchRolePicklistValues() {
        List<String> roles = DependentPicklist.getDependentPicklistValues( Account_Team_And_Authorizations__c.Type__c,
                'Account Team');
        return roles;

        /*
       	Map<String, Schema.SObjectField> fieldMap = Schema.getGlobalDescribe().get('Contract__c').getDescribe().fields.getMap();
		List<String> values = new List<String>();

        Set<String> apiNameFields = new Set<String>();
        for(APTask_Roles__mdt role : [SELECT Label, Contract_field__c, Default_for_custom_task__c, Nickname__c, Type__c
            FROM APTask_Roles__mdt]){
            apiNameFields.add(role.Contract_field__c);
        }

        for (String field : apiNameFields) {
            values.add(fieldMap.get(field).getDescribe().getLabel());
        }
        values.add(AptTemplateController.ACCOUNT_OWNER);

*/

        /*
        values.add(fieldMap.get('Employee_1__c').getDescribe().getLabel());
        values.add(fieldMap.get('Employee_2__c').getDescribe().getLabel());
        values.add(fieldMap.get('Employee_3__c').getDescribe().getLabel());
        values.add(fieldMap.get('Employee_4__c').getDescribe().getLabel());
        values.add(fieldMap.get('CertifiedAccountant__c').getDescribe().getLabel());
        values.add(fieldMap.get('CustomerResponsibleAndRemittanceResp__c').getDescribe().getLabel());
        values.add(fieldMap.get('IntegrationResource__c').getDescribe().getLabel());
        values.add(fieldMap.get('PayrollOfficer__c').getDescribe().getLabel());
        values.add(fieldMap.get('ProjectManager__c').getDescribe().getLabel());
         */

    }


}