force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Account_SPGroupId__c.field-meta.xml
<CustomField>
    <fullName>Account_SPGroupId__c</fullName>
    <formula>Kontrakt__r.Account__r.SPGroupID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account SPGroupId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oppdragsteam_Fullmakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Responsible_Email__c.field-meta.xml
<CustomField>
    <fullName>Responsible_Email__c</fullName>
    <formula>Responsible__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Responsible Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/MSTeamsOwnersRoles__c/MSTeamsOwnersRoles__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used for Account Team And Authorizations  to  add Owners list with comma separate values from Type field values</description>
    <label>MSTeamsOwnersRoles</label>
</CustomObject>

force-app/main/default/objects/MSTeamsOwnersRoles__c/fields/ListOwners__c.field-meta.xml
<CustomField>
    <fullName>ListOwners__c</fullName>
    <description>Add Owners with comma separate values</description>
    <label>ListOwners</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccTeamAndAuthTriggerHandlerQueueablecls.cls
global class AccTeamAndAuthTriggerHandlerQueueablecls implements Queueable , Database.AllowsCallouts  {
    
    List<Account_Team_And_Authorizations__c> accTeamAuthLst = new List<Account_Team_And_Authorizations__c>();
    String operationType;
    
    
    global AccTeamAndAuthTriggerHandlerQueueablecls(List<Account_Team_And_Authorizations__c> accTeamAuthLst, String operationType){
        
        this.accTeamAuthLst = accTeamAuthLst;
        this.operationType = operationType;
              
    }
    
    global void execute(QueueableContext context) {
        try {
            List<string> MSOwnerRolesList;
            MSTeamsOwnersRoles__c MSOwnerRoles =[select ListOwners__c from MSTeamsOwnersRoles__c];
            
            if(MSOwnerRoles.ListOwners__c!=null){
                MSOwnerRolesList = MSOwnerRoles.ListOwners__c.split(',');
            }
            Map<string,List<Account_Team_And_Authorizations__c>> accAtMap = new Map<string,List<Account_Team_And_Authorizations__c>>();
            for(Account_Team_And_Authorizations__c actma : accTeamAuthLst){
                
                String groupid = actma.Account_SPGroupId__c;
                System.debug('Group ID:' +groupid);
                if(string.isNotEmpty(groupid) && actma.Responsible__c != null){
                if(accAtMap.containsKey(groupid)){
                    List<Account_Team_And_Authorizations__c> tempActmaLst = accAtMap.get(groupid);
                    tempActmaLst.add(actma);
                    accAtMap.put(groupid,tempActmaLst);
                    
                }
                else{
                    accAtMap.put(groupid,new List<Account_Team_And_Authorizations__c> {actma});
                }
                }
            }
            
            if(!accAtMap.isEmpty()){
            map<string, object> mapToSerialize = new map<string, object>();
            for (String groupId : accAtMap.keySet()) {
                mapToSerialize.put('groupId', groupId);
                
                
                
                List<map<String, String>> getOwnerList = new List<map<String, String>>();
                List<map<String, String>> memberList = new List<map<String, String>>();
                for (Account_Team_And_Authorizations__c act : accAtMap.get(groupId)) {
                    
                    // Check if the account team and authorization record type is in the MSOwnerRolesList
                    if (MSOwnerRolesList.contains(act.Type__c) || act.Type__c == 'Account_Owner' || act.Type__c == 'Oppdragsansvarlig') {
                        // Create a map for the owner and add it to the owner list
                        map<string, string> ownerMap = new map<string, string>();
                        ownerMap.put('email', act.Responsible_Email__c);
                        ownerMap.put('operationType', operationType);
                        getOwnerList.add(ownerMap);
                        system.debug('getOwnerList'+ getOwnerList);
                        
                    } else {
                        // If the account team and authorization record type is not in the MSOwnerRolesList, 
                        // get the member types using the ATATMembers class and loop through each member type
                        List<String> strList = ATATMembers.GetTypes(act.Type__c);
                        for (String str : strList) {
                            // Create a map for the member and add it to the member list
                            map<string, string> memberMap = new map<string, string>();
                            memberMap.put('email', act.Responsible_Email__c);
                            memberMap.put('channelName', str);
                            memberMap.put('operationType',operationType);
                            memberList.add(memberMap);
                            system.debug('memberList'+memberList);
                            
                        }
                        
                    }
                }
                mapToSerialize.put('owners', getOwnerList);
                mapToSerialize.put('members', memberList);
                
                System.debug('Map before serialization: ' + mapToSerialize);
                string body = JSON.serialize(mapToSerialize);
                System.debug('Body after serialization: ' + body);
                AccountTeamAndAuthCallOutHandller.addMembersAndOwners(body,groupId);
                System.debug(body);
            }  
            }
        }
        
        catch(Exception ex) {
            system.debug('Error on AccTeamAndAuthTriggerHandlerQueueablecls-->'+ex.getMessage());
        }
    }
}