force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptAssignedRoleFieldController.cls
/**
 * @author Jozef 
 * @date 11.9.2019.
 * @description //TODO
 */

public with sharing class AptAssignedRoleFieldController {
    private Task task;
    public String label {get; set;}
    public String value {get; set;}


    public AptAssignedRoleFieldController(ApexPages.StandardController controller){
        Task t = (Task)controller.getrecord();
        this.task = [SELECT Assigned_Role__c FROM Task WHERE id=: t.id];
        this.label = Schema.getGlobalDescribe().get('Task').getDescribe().
                fields.getMap().get('Assigned_Role__c').getDescribe().getLabel();
        Map<String, String> assignedRoleTranslationApi = DependentPicklist.getPicklistApiMap(
                Account_Team_And_Authorizations__c.Type__c);
        this.value = assignedRoleTranslationApi.get(task.Assigned_Role__c);
    }

}