force-app/main/default/objects/Account_Team_And_Authorizations__c/Account_Team_And_Authorizations__c.object-meta.xml
<CustomObject>
    <description>This object is used when creating Account Team and Authorizations related to the kontrakt</description>
    <label>Account Team And Authorizations</label>
    <nameField>
        <displayFormat>OT-{0000}</displayFormat>
        <label>Account Team And Authorizations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team And Authorizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <inlineHelpText>Oppdragsteam og Fullmakter</inlineHelpText>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account_Team</fullName>
                <default>true</default>
                <label>Account Team</label>
            </value>
            <value>
                <fullName>Authorizations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Bypass_Validation_Rule__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Validation_Rule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to allow Kontrakt Process to update Account Owner and Authorized Accountant</description>
    <label>Bypass Validation Rule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Kontrakt__c.field-meta.xml
<CustomField>
    <fullName>Kontrakt__c</fullName>
    <label>Kontrakt</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Oppdragsteam_Fullmakter</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Responsible__c.field-meta.xml
<CustomField>
    <fullName>Responsible__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsible</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oppdragsteam_Fullmakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Team_And_Authorizations__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Area__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Oppdragsteam_Fullmakter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/APTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Task detail</description>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTaskTemplate__c/fields/ActionPlanTemplate__c.field-meta.xml
<CustomField>
    <fullName>ActionPlanTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Action plan template from which was task created in ActionPlan. Used to identify when task from various templates are in the ActionPlan (for example when ActionPlan is generated from Contract with predefined various templates using)</description>
    <label>AP Template</label>
    <referenceTo>ActionPlanTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/APT_Task__c.field-meta.xml
<CustomField>
    <fullName>APT_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APT Task</label>
    <referenceTo>APTTaskTemplate__c</referenceTo>
    <relationshipLabel>AP Tasks</relationshipLabel>
    <relationshipName>AP_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values in custom settings.</description>
    <label>Assigned Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_10__c.field-meta.xml
<CustomField>
    <fullName>Period_10__c</fullName>
    <label>Period 10</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_3__c.field-meta.xml
<CustomField>
    <fullName>Period_3__c</fullName>
    <label>Period 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period 4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period 5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period 6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Period_7__c.field-meta.xml
<CustomField>
    <fullName>Period_7__c</fullName>
    <label>Period 7</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/Skip_Weekends__c.field-meta.xml
<CustomField>
    <fullName>Skip_Weekends__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip Weekends</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTaskTemplate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Initial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Start_Date__c</fullName>
    <label>Initial Start Date</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reporting Date</fullName>
            </value>
            <value>
                <fullName>Payroll Date</fullName>
            </value>
            <value>
                <fullName>Year end reporting date</fullName>
            </value>
            <value>
                <fullName>Closing date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_11__c.field-meta.xml
<CustomField>
    <fullName>Period_11__c</fullName>
    <label>Period 11</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_12__c.field-meta.xml
<CustomField>
    <fullName>Period_12__c</fullName>
    <label>Period 12</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_1__c.field-meta.xml
<CustomField>
    <fullName>Period_1__c</fullName>
    <label>Period 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_2__c.field-meta.xml
<CustomField>
    <fullName>Period_2__c</fullName>
    <label>Period 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_4__c.field-meta.xml
<CustomField>
    <fullName>Period_4__c</fullName>
    <label>Period  4</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_5__c.field-meta.xml
<CustomField>
    <fullName>Period_5__c</fullName>
    <label>Period  5</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_6__c.field-meta.xml
<CustomField>
    <fullName>Period_6__c</fullName>
    <label>Period  6</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_8__c.field-meta.xml
<CustomField>
    <fullName>Period_8__c</fullName>
    <label>Period 8</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_9__c.field-meta.xml
<CustomField>
    <fullName>Period_9__c</fullName>
    <label>Period 9</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Plus_Days__c.field-meta.xml
<CustomField>
    <fullName>Plus_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Plus Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00NR0000000Vd65MAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account_Owner_KA__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_KA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Kundeansvarlig</inlineHelpText>
    <label>Account Owner (KA)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Kontrakter</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Year_end_reporting_date__c.field-meta.xml
<CustomField>
    <fullName>Year_end_reporting_date__c</fullName>
    <label>Year end reporting date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AptActionPlanSyncTest.cls
/**
 * Created by jozef on 12. 5. 2023.
 */

@IsTest
private class AptActionPlanSyncTest {
    @TestSetup static void setup() {
        AptUtilDataTest.setup();
        AptUtilDataTest.createStandardTasks();
        Contract__c contract = [SELECT id, Account_Owner_KA__c FROM Contract__c LIMIT 1];
        contract.Account_Owner_KA__c = UserInfo.getUserId();
        update contract;
    }

    static void validateResult(Account_Team_And_Authorizations__c at){
        List<APTaskTemplate__c> actionPlanTemplatesAll = [SELECT id, User__c, Assigned_Role__c FROM APTaskTemplate__c];
        List<APTaskTemplate__c> actionPlanTemplates = [SELECT id, User__c, Assigned_Role__c FROM APTaskTemplate__c
        WHERE User__c =: at.Responsible__c AND Assigned_Role__c =: at.Type__c];
        //System.debug('All ----------->' + actionPlanTemplatesAll);
        //System.debug('just ----------->' + actionPlanTemplates);
        Assert.areEqual(actionPlanTemplatesAll.size(), actionPlanTemplates.size());
        List<Task> tasksAll = [SELECT id, OwnerId FROM Task];
        List<Task> tasks = [SELECT id, OwnerId FROM Task WHERE OwnerId =: at.Responsible__c ];
        Assert.areEqual(tasksAll.size(), tasks.size());
    }

    @IsTest
    static void insertAccountTeamTest() {
        Account_Team_And_Authorizations__c at = getAccountTeamAndAuthorizations(null);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        insert at;
        Test.stopTest();
        at = [SELECT Type__c, Responsible__r.Name, Responsible__c FROM Account_Team_And_Authorizations__c
        WHERE Type__c = 'Payroll_Responsible'];
        validateResult(at);
    }

    static Account_Team_And_Authorizations__c getAccountTeamAndAuthorizations(User newUser){
        if (newUser == null){
            Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
            newUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                    LocaleSidKey='en_US', ProfileId = p.Id,
                    TimeZoneSidKey='America/Los_Angeles', UserName='aptactionplantest@testorg.com');
            insert newUser;
        }
        Contract__c contract = [SELECT id, Account_Owner_KA__c FROM Contract__c LIMIT 1];
        Account_Team_And_Authorizations__c at = new Account_Team_And_Authorizations__c();
        at.Kontrakt__c = contract.id;
        at.Area__c = 'Account_Team';
        at.Type__c = 'Payroll_Responsible';
        at.Responsible__c = newUser.id;
        at.Bypass_Validation_Rule__c = true;
        return at;
    }

    @IsTest
    static void updateAccountTeamTest() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User newUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='aptactionplantest2@testorg.com');
        insert newUser;
        Account_Team_And_Authorizations__c atOne = getAccountTeamAndAuthorizations(null);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        insert atOne;
        atOne.Responsible__c = newUser.id;
        update atOne;
        Test.stopTest();
        atOne = [SELECT Type__c, Responsible__r.Name, Responsible__c FROM Account_Team_And_Authorizations__c
        WHERE Type__c = 'Payroll_Responsible'];
        validateResult(atOne);
    }

    @IsTest
    static void deleteAccountTeamTest() {
        Account_Team_And_Authorizations__c atOne = getAccountTeamAndAuthorizations(null);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        insert atOne;
        delete atOne;
        Test.stopTest();
        Account_Team_And_Authorizations__c at = [SELECT Type__c, Responsible__r.Name, Responsible__c
        FROM Account_Team_And_Authorizations__c
        WHERE Type__c = 'Account_Owner'];
        validateResult(at);
    }

    @IsTest
    static void updateYearAndReportingDateTest() {
        List<APTTaskTemplate__c> aptTaskTemplates = [SELECT id, Plus_Days__c FROM APTTaskTemplate__c];
        for (APTTaskTemplate__c apttTaskTemplate : aptTaskTemplates) {
            apttTaskTemplate.Plus_Days__c = 10;
        }
        update aptTaskTemplates;
        Contract__c contract = [SELECT Id, Year_end_reporting_date__c FROM Contract__c];
        Integer thisYear = System.today().year();
        contract.Year_end_reporting_date__c = Date.newInstance(thisYear,1,1);
        Test.startTest();
        update contract;
        Test.stopTest();
        List<APTaskTemplate__c> apTaskTemplates = [SELECT id,
                Period_1__c,
                Period_2__c, Period_3__c, Period_4__c, Period_5__c,
                Period_6__c, Period_7__c, Period_8__c, Period_9__c, Period_10__c,
                Period_11__c, Period_12__c, Skip_Weekends__c, Reminder__c, ActionPlanTemplate__r.Name,
                APT_Task__r.Initial_Start_Date__c
        FROM APTaskTemplate__c];
        System.debug(apTaskTemplates);
        List<Task> tasks = [SELECT id, ActivityDate, Period__c, Status FROM Task ];
        System.debug(tasks);
        //Follow 5-fifth period. 5th period is not static,
        //it is calculated from year end reporting date Period_5__c=2023-05-01 00:00:00
    }


}