force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/IsMandatory__c.field-meta.xml
<CustomField>
    <fullName>IsMandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify mandatory task - if it is then removing from action is disabled.</description>
    <inlineHelpText>Is task mandatory?</inlineHelpText>
    <label>Is Mandatory</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>TaskId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptTaskUploadSelectorController.cls
public class AptTaskUploadSelectorController {
	@AuraEnabled
    public static Map<String, List<APTTaskTemplate__c>> fetchAPTaskTempates(String templateType, String conId) {
        System.debug('fetchAPTaskTempates = ' + templateType + ' ' + conId);
        List<APTTaskTemplate__c> selTaskTemplates = new List<APTTaskTemplate__c>();
        Map <String, List<APTTaskTemplate__c>> apNameToAptTask= new Map<String, List<APTTaskTemplate__c>>();
        Boolean isLibrary = true;
        if (templateType == 'template'){
            isLibrary = false;
            Contract__c contract = [SELECT id, Scope__c FROM Contract__c WHERE id =: conId];
            if (contract.Scope__c != null) {
                System.debug(contract.Scope__c);
                Set<String> scopeFilter = new Set<String>(contract.Scope__c.split(';'));
                selTaskTemplates = [
                        SELECT Id, Name, Task_Number__c,TaskId__c,IsMandatory__c, Frequency__c,
                                Assigned_Role__c, Subject__c, Action_Plan_Template__r.Name
                        FROM APTTaskTemplate__c
                        WHERE Action_Plan_Template__r.Name IN : scopeFilter];
            }
        }else{
            selTaskTemplates = [SELECT Id, Name, Task_Number__c,TaskId__c,IsMandatory__c, Frequency__c,
                    Assigned_Role__c, Subject__c, Action_Plan_Template__r.Name
            FROM APTTaskTemplate__c WHERE Action_Plan_Template__r.Library_Template__c =: isLibrary];
        }
        for (APTTaskTemplate__c aptt : selTaskTemplates) {
            if (apNameToAptTask.containsKey(aptt.Action_Plan_Template__r.Name)) {
                apNameToAptTask.get(aptt.Action_Plan_Template__r.Name).add(aptt);
            } else {
                apNameToAptTask.put(aptt.Action_Plan_Template__r.Name, new List<APTTaskTemplate__c>{aptt});
            }
        }
        return apNameToAptTask;
    }
}