force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptAssignedRoleFieldControllerTest.cls
/**
 * @author Jozef 
 * @date 12.9.2019.
 * @description //TODO
 */

@IsTest
private class AptAssignedRoleFieldControllerTest {
    @testSetup static void setup() {
        AptUtilDataTest.setup();
    }

    @IsTest
    static void controllerTest() {
        //PageReference pageRef = Page.AptAssignedRoleField;
        //Test.setCurrentPage(pageRef);
        /*
        List<APTTaskTemplate__c> lt = [SELECT id, Assigned_Role__c FROM APTTaskTemplate__c
            WHERE Assigned_Role__c = 'Account Owner' OR Assigned_Role__c = 'Payroll Officer'];
        System.debug('TO BE DONE:' + lt.size());
        for (APTTaskTemplate__c aptTaskTemplate : lt) {
            if (aptTaskTemplate.Assigned_Role__c == 'Account Owner'){
                aptTaskTemplate.Assigned_Role__c = 'Account_Owner';
            }else if(aptTaskTemplate.Assigned_Role__c == 'Payroll Officer'){
                aptTaskTemplate.Assigned_Role__c = 'Payroll_Responsible';
            }
        }
        if (!lt.isEmpty()){
            update lt;
        }
         */


        Task t = new Task();
        t.AP_Task__c = AptUtilDataTest.createActionPlanTasks(1).get(0).id;
        insert t;


        Test.startTest();
        //Test.setMock(HttpCalloutMock.class, new AptContractTriggerHandlerMock.CreateTeamSiteHelper_Mock());
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        ApexPages.StandardController std = new   ApexPages.StandardController(t);
        AptAssignedRoleFieldController controller = new AptAssignedRoleFieldController(std);
        System.assert(controller.label != null);
        System.assert(controller.value != null);
        Test.stopTest();
    }
}