force-app/main/default/objects/AttachmentHeader__c/AttachmentHeader__c.object-meta.xml
<CustomObject>
    <label>AttachmentHeader</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttachmentHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttachmentHeader__c/fields/Contract_Id__c.field-meta.xml
<CustomField>
    <fullName>Contract_Id__c</fullName>
    <label>Contract_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AttachmentHeader__c/fields/Standard_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Standard_Task_Id__c</fullName>
    <label>Standard_Task_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AttachmentRow__c/AttachmentRow__c.object-meta.xml
<CustomObject>
    <label>AttachmentRow</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AttachmentRow Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttachmentRows</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AttachmentRow__c/fields/AttachmentHeader__c.field-meta.xml
<CustomField>
    <fullName>AttachmentHeader__c</fullName>
    <label>AttachmentHeader</label>
    <referenceTo>AttachmentHeader__c</referenceTo>
    <relationshipLabel>AttachmentRows</relationshipLabel>
    <relationshipName>AttachmentRows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AptFilesListController.cls
public class AptFilesListController {

    @AuraEnabled
    public static List<ContentVersion> fetchFiles(String relatedRecordId) {
        /*List<AttachmentHeader__c> attHeaders = [SELECT Id, Name, Standard_Task_Id__c, Contract_Id__c 
                                                FROM AttachmentHeader__c WHERE Standard_Task_Id__c = :relatedRecordId];*/
        Set<Id> attHeadersIds = new Set<Id>();
        for (AttachmentHeader__c ah : [SELECT Id, Name, Standard_Task_Id__c, Contract_Id__c 
                                                FROM AttachmentHeader__c WHERE Standard_Task_Id__c = :relatedRecordId]) {
                                                    
            attHeadersIds.add(ah.Id);
        }
        
        List<AttachmentRow__c> attRows = [SELECT Id, File_Name__c, AttachmentHeader__c 
                                          FROM AttachmentRow__c WHERE AttachmentHeader__c IN :attHeadersIds];
        
        Map<Id,List<Id>> documentLink = new Map<Id,List<Id>>();
        for(ContentDocumentLink cdl : [SELECT id, ContentDocument.id
        								FROM ContentDocumentLink WHERE linkedentityid = :relatedRecordId]) {

            if (documentLink.containsKey(cdl.ContentDocument.id)){
                documentLink.get(cdl.ContentDocument.id).add(cdl.id);
            }else{
                List<Id> cdlIds = new List<Id>();
                cdlIds.add(cdl.id);
                documentLink.put(cdl.ContentDocument.id, cdlIds);
            }
        }

        List<ContentVersion> cvs = [SELECT id,
                Description,
                Title,
                PathOnClient,
                ContentLocation,
                ExternalDataSourceId,
                ExternalDocumentInfo1,
                ExternalDocumentInfo2,
                Origin,
                ContentDocumentId,
                ContentDocument.Title,
                LastModifiedDate,
                CreatedById,
                OwnerId,
                Owner.Name,
                CreatedBy.Name                   
        FROM ContentVersion
        WHERE ContentDocumentId IN: documentLink.keySet()
        AND IsLatest = true
        ORDER BY LastModifiedDate desc];
       
        System.debug(cvs);
        return cvs;
     }
}