force-app/main/default/objects/AttachmentHeader__c/AttachmentHeader__c.object-meta.xml
<CustomObject>
    <label>AttachmentHeader</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Attachment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AttachmentHeaders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AttachmentHeader__c/fields/Standard_Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Standard_Task_Id__c</fullName>
    <label>Standard_Task_Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AptFilesListControllerTest.cls
/**
 * @author Jozef 
 * @date 6.9.2019.
 * @description //TODO
 */

@IsTest
private class AptFilesListControllerTest {

    @IsTest
    static void fetchFilesTest() {
        Task task = new Task();
        insert task;

        ContentVersion contentVersionInsert = AptUtilDataTest.createContentVersion();

        AttachmentHeader__c attachmentHeader = AptUtilDataTest.createAttachmentHeader();
        attachmentHeader.Standard_Task_Id__c = task.id;
        update attachmentHeader;
        String relatedRecordId = task.id;

        ContentVersion cv = [SELECT id, ContentDocumentId FROM ContentVersion WHERE id=:contentVersionInsert.id];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = cv.ContentDocumentId;
        cdl.LinkedEntityId = task.id;
        cdl.ShareType = 'V';
        insert cdl;

        Test.startTest();
        AptFilesListController.fetchFiles(relatedRecordId);
        Test.stopTest();
    }
}