force-app/main/default/objects/AzureAD_Credential__c/AzureAD_Credential__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AzureAD Credential</label>
</CustomObject>

force-app/main/default/objects/AzureAD_Credential__c/fields/ClientSecretKey__c.field-meta.xml
<CustomField>
    <fullName>ClientSecretKey__c</fullName>
    <label>ClientSecretKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AzureAD_Credential__c/fields/DevAPIEndPoint__c.field-meta.xml
<CustomField>
    <fullName>DevAPIEndPoint__c</fullName>
    <defaultValue>&apos;https://devviewledgerapi.azurewebsites.net/api/&apos;</defaultValue>
    <label>DevAPIEndPoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AzureAD_Credential__c/fields/Salesforce_ClientId__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ClientId__c</fullName>
    <label>Salesforce ClientId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AzureAD_Credential__c/fields/Salesforce_ClientSecret__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ClientSecret__c</fullName>
    <label>Salesforce ClientSecret</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountTeamAndAuthCallOutHandller.cls
public class AccountTeamAndAuthCallOutHandller {
    
    // This method will run asynchronously and make a callout to an external service
    @future(Callout=true)
    public static void addMembersAndOwners(String body,String GroupId) {
        try {
            // Retrieve AzureAD credentials from a custom object
            AzureAD_Credential__c objAzureCredential = [Select DevAPIEndPoint__c, ClientId__c, ClientSecretKey__c,Salesforce_ClientId__c,Salesforce_ClientSecret__c FROM AzureAD_Credential__c];
            
            // Retrieve AzureAD credentials from a custom object
            String endpoint = objAzureCredential.DevAPIEndPoint__c + 'api/UserManagement/UserManagement';
            String authorization = objAzureCredential.Salesforce_ClientId__c + objAzureCredential.Salesforce_ClientSecret__c;
            
            // Make the callout to the external service and capture the response
            HttpResponse response = GlobalAPICallOut.makeCallout(body, endpoint, 'POST', authorization);
            String responseBody = response.getBody();
            Integer statusCode = response.getStatusCode();
            String statusMessage = response.getStatus();
            
            System.debug('responseBody: ' + responseBody);
            System.debug('statusCodeTeam: ' + statusCode);
            System.debug('statusMessage: ' + statusMessage);
            
            // Log the response information to a custom object
            CreateCustomLogHandler.addCustomlogUserManagement(responseBody,statusCode,statusMessage,GroupId);
        }catch (Exception e) {
            // Handle the exception here
            System.debug('Exception caught: ' + e.getMessage());
            
        }
    }       
}