force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActionPlanTemplate__c/fields/Library_Template__c.field-meta.xml
<CustomField>
    <fullName>Library_Template__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Library Template</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Kontrakt</label>
    <nameField>
        <displayFormat>K-{YYYY}{MM}-{0}</displayFormat>
        <label>Serial Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kontrakter</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Scope__c.field-meta.xml
<CustomField>
    <fullName>Scope__c</fullName>
    <inlineHelpText>Test</inlineHelpText>
    <label>Scope</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Delivery__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Templates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AptTaskUploadSelectorControllerTest.cls
@IsTest
private class AptTaskUploadSelectorControllerTest {

    @IsTest
    static void fetchAPTaskTempatesLibraryTest() {
        List<APTTaskTemplate__c> lAptTaskTemplates = AptUtilDataTest.createTemplateTasks(2);

        APTTaskTemplate__c apt = lAptTaskTemplates.get(0);
        ActionPlanTemplate__c actionPlanTemplate = [SELECT id, Library_Template__c FROM ActionPlanTemplate__c
            WHERE id =: apt.Action_Plan_Template__c];
        actionPlanTemplate.Library_Template__c = true;
        update actionPlanTemplate;

        Test.startTest();
        AptTaskUploadSelectorController.fetchAPTaskTempates('library', null);
        Test.stopTest();
    }

    @IsTest
    static void fetchAPTaskTempatesTest() {
        AptUtilDataTest.setup();
        List<APTTaskTemplate__c> lAptTaskTemplates = AptUtilDataTest.createTemplateTasks(2);
        Contract__c contract = AptUtilDataTest.createContract();

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AptAccountTeamAndAuthTriggerHandlerMock.MsCallout_Mock());
        contract.Scope__c = '';
        update contract;

        AptTaskUploadSelectorController.fetchAPTaskTempates('template', contract.id);
        Test.stopTest();
    }

}