force-app/main/default/objects/ActionPlanTemplate__c/ActionPlanTemplate__c.object-meta.xml
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/APTTaskTemplate__c.object-meta.xml
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/APTTaskTemplate__c/fields/Assigned_Role__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Role__c</fullName>
    <description>Replacement field for Assigned Type. Values from custom settings.</description>
    <label>Assigned Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Certified Accountant</fullName>
            </value>
            <value>
                <fullName>Customer Responsible and Remittance Resp</fullName>
            </value>
            <value>
                <fullName>Employee 1</fullName>
            </value>
            <value>
                <fullName>Employee 2</fullName>
            </value>
            <value>
                <fullName>Employee 3</fullName>
            </value>
            <value>
                <fullName>Employee 4</fullName>
            </value>
            <value>
                <fullName>Integration Resource</fullName>
            </value>
            <value>
                <fullName>Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Account Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Interim</fullName>
            </value>
            <value>
                <fullName>Biannual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_1__c.field-meta.xml
<CustomField>
    <fullName>Period_1__c</fullName>
    <label>Period 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Period_2__c.field-meta.xml
<CustomField>
    <fullName>Period_2__c</fullName>
    <label>Period 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Task_Number__c</fullName>
    <label>Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/APTTaskTemplate__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>R00NR0000000Vd65MAC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AptTemplateControllerTest.cls
/**
 * @author Jozef 
 * @date 5.9.2019.
 * @description //TODO
 */

@IsTest
private class AptTemplateControllerTest {
    @IsTest
    static void getTemplatePlanTest() {
        Id recordId = AptUtilDataTest.createTemplatePlan().id;
        Test.startTest();
        AptTemplateController.getTemplatePlan(recordId);
        Test.stopTest();
    }

    @IsTest
    static void getTasksTest() {
        List<APTTaskTemplate__c> tTasks = AptUtilDataTest.createTemplateTasks(2);
        Id apId = tTasks.get(0).Action_Plan_Template__c;
        Test.startTest();
        AptTemplateController.getTasks(apId);
        Test.stopTest();
    }

    @IsTest
    static void getNewTemplatePlanTaskTest() {
        AptTemplateController.getNewTemplatePlanTask('0');
    }

    @IsTest
    static void fetchRolePicklistValuesTest() {
        AptTemplateController.fetchRolePicklistValues();
    }

    @IsTest
    static void fetchIniStartDatePicklistValuesTest() {
        AptTemplateController.fetchIniStartDatePicklistValues();
    }


    @IsTest
    static void saveTemplatePlanNewTest() {
        Id tId = null;
        ActionPlanTemplate__c tPlan = new ActionPlanTemplate__c(Name = 'Test Template One');
        String userId = UserInfo.getUserId();
        String tTasksJSON = '[{"taskIndex__c":0,' +
                '"User__c":"'+ userId + '","IsVisible__c":true,"Id":null,' +
                '"Frequency__c":"Biannual","Assigned_Role__c":"Payroll Responsible",' +
                '"Task_Number__c":"230","Subject__c":"Test Subject","Period_1__c":"2019-09-07"},' +
                '{"taskIndex__c":1,"User__c":"'+ userId + '","IsVisible__c":true,"Id":null,' +
                '"Frequency__c":"Biannual","Assigned_Role__c":"Payroll Responsible","Task_Number__c":"231",' +
                '"Subject__c":"Test Subject second","Period_2__c":"2019-09-07"}]';
        String delTasksJSON = '[]';
        AptTemplateController.savePlan(tId, tPlan , tTasksJSON, delTasksJSON);
    }
}